import { GDEntryTypeConfig, GDTemplate } from "@/types/generalDiary";

export const INITIAL_GD_TYPES: GDEntryTypeConfig[] = [
  {
    code: "AAGAZ_ROZNAMCHA",
    category: "ROUTINE_ADMINISTRATION",
    nameEn: "Opening / Aagaz Roznamcha",
    nameHi: "आगाज़ रोजनामचा (दैनिक शुरुआत 08:00 AM)",
    description: "Daily commencement of General Diary at 08:00 hrs with weapon inventory, hawalat status, cash & vehicle accounting under PPR 22.48.",
    isEnabled: true,
    usedCount: 14,
    requiresOfficer: false,
    defaultTemplates: [
      {
        id: "tmpl_aagaz_hi",
        typeCode: "AAGAZ_ROZNAMCHA",
        title: "दैनिक आगाज़ रोजनामचा (मानक हिंदी)",
        titleHi: "आगाज़ रोजनामचा - मानक",
        language: "hi",
        subjectTemplate: "बवक्त 08:00 AM आगाज़ रोजनामचा आम बाबत खैर-ओ-आफियत थाना",
        bodyTemplate:
          "बवक्त 08:00 बजे सुबह, रोजनामचा आम का नया पन्ना/जिल्द विधिवत शुरू किया गया। रात की पाली शांत व खैरियत से गुजरी। मुआयना हवालात किया गया, हवालात में कुल {{hawalatCount}} बंदी मौजूद हैं, जिनकी शारीरिक व मानसिक स्थिति ठीक पाई गई। सरकारी शस्त्रागार (Kot) में कुल असलहा व कारतूस बामुताबिक रजिस्टर पूरे पाए गए। सरकारी खजाना व रोकड़ बहिरू चेक की गई। स्टेशन डायरी का प्रभार MHC {{mhcName}} (बेल्ट नं: {{mhcBeltNo}}) द्वारा संभाला गया। थाना परिसर में शांति व व्यवस्था कायम है।",
        variables: [
          { key: "hawalatCount", labelHi: "हवालात में बंदी संख्या", labelEn: "Hawalat Detainees", type: "number", required: true, defaultValue: "0" },
          { key: "mhcName", labelHi: "ड्यूटी MHC का नाम", labelEn: "MHC Name", type: "text", required: true, autoFillSource: "currentUser" },
          { key: "mhcBeltNo", labelHi: "MHC बेल्ट नंबर", labelEn: "MHC Belt No", type: "text", required: true, defaultValue: "889/KKR" },
        ],
        isDefault: true,
      },
      {
        id: "tmpl_aagaz_en",
        typeCode: "AAGAZ_ROZNAMCHA",
        title: "Daily Commencement (English Legal)",
        titleHi: "Opening of Roznamcha (English)",
        language: "en",
        subjectTemplate: "At 08:00 hrs Commencement of Daily General Diary (Register No. II)",
        bodyTemplate:
          "At 08:00 hours, the General Diary for the 24-hour cycle was duly opened in accordance with Punjab Police Rule 22.48. Sentry relief and lockup inspection conducted. Current lockup strength: {{hawalatCount}} detainee(s), in sound physical health. Station armory, ammunition registers, and cash chest verified. Sentry guard and MHC charge assumed by {{mhcName}} (Belt: {{mhcBeltNo}}). All station affairs reported in order.",
        variables: [
          { key: "hawalatCount", labelHi: "हवालात में बंदी संख्या", labelEn: "Hawalat Detainees", type: "number", required: true, defaultValue: "0" },
          { key: "mhcName", labelHi: "ड्यूटी MHC का नाम", labelEn: "MHC Name", type: "text", required: true, autoFillSource: "currentUser" },
          { key: "mhcBeltNo", labelHi: "MHC बेल्ट नंबर", labelEn: "MHC Belt No", type: "text", required: true, defaultValue: "889/KKR" },
        ],
      },
    ],
  },
  {
    code: "BANDI_ROZNAMCHA",
    category: "ROUTINE_ADMINISTRATION",
    nameEn: "Closing / Bandi Roznamcha",
    nameHi: "बंदी रोजनामचा (24 घंटे का समापन)",
    description: "24-hour formal closure of General Diary summarizing total daily entries, hawalat status, pending process & handover under PPR 22.49.",
    isEnabled: true,
    usedCount: 12,
    requiresOfficer: false,
    defaultTemplates: [
      {
        id: "tmpl_bandi_hi",
        typeCode: "BANDI_ROZNAMCHA",
        title: "बंदी रोजनामचा आम (हिंदी)",
        titleHi: "बंदी रोजनामचा",
        language: "hi",
        subjectTemplate: "बवक्त 08:00 AM बंदी रोजनामचा आम 24 घंटे व कुल रपट संख्या",
        bodyTemplate:
          "बवक्त 08:00 बजे सुबह, 24 घंटे का रोजनामचा आम मुकम्मल तौर पर बंद किया जाता है। पिछले 24 घंटों में रपट नंबर 01 से लेकर रपट नंबर {{lastGdNo}} तक कुल {{totalEntries}} प्रविष्टियां दर्ज की गईं। हवालात में इस वक्त कुल {{hawalatCount}} मुलजिम बंद हैं। सभी सरकारी हथियार, मालखाना संपत्तियां व स्टेशन डायरी अगले 24 घंटे के लिए नए रजिस्टर में स्थानांतरित की जा रही हैं। कोई अप्रिय घटना घटित नहीं हुई।",
        variables: [
          { key: "lastGdNo", labelHi: "अंतिम रपट नंबर", labelEn: "Last GD Number", type: "number", required: true, defaultValue: "28" },
          { key: "totalEntries", labelHi: "कुल दैनिक प्रविष्टियां", labelEn: "Total Entries", type: "number", required: true, defaultValue: "28" },
          { key: "hawalatCount", labelHi: "मौजूदा बंदी संख्या", labelEn: "Lockup Count", type: "number", required: true, defaultValue: "1" },
        ],
        isDefault: true,
      },
    ],
  },
  {
    code: "STAFF_GINTI",
    category: "ROUTINE_ADMINISTRATION",
    nameEn: "Staff Ginti / Roll Call",
    nameHi: "हाज़िरी व गिनती मुलाज़मान (Roll Call)",
    description: "Daily morning/evening parade roll call, present strength, leave/sick/absent accounting and beat distribution.",
    isEnabled: true,
    usedCount: 22,
    requiresOfficer: false,
    defaultTemplates: [
      {
        id: "tmpl_ginti_hi",
        typeCode: "STAFF_GINTI",
        title: "हाज़िरी व गिनती मुलाज़मान (हिंदी)",
        titleHi: "गिनती मुलाज़मान",
        language: "hi",
        subjectTemplate: "बवक्त सुबह/शाम गिनती मुलाज़मान व तक्सीम ड्यूटी थाना",
        bodyTemplate:
          "थाना परिसर में दैनिक गिनती मुलाज़मान ली गई। कुल स्वीकृत नफरी में से {{presentCount}} मुलाज़मान हाज़िर मिले। {{leaveCount}} मुलाज़िम छुट्टी (Leave) पर व {{sickCount}} मुलाज़िम गैर-हाज़िर/बीमार पाए गए। हाज़िर मुलाज़मान का टर्नआउट, वर्दी व हथियार दुरुस्त पाए गए। सभी कर्मचारियों को उच्चाधिकारियों के निर्देशों की पालना, आम जनता से शिष्ट व्यवहार एवं मुस्तैदी से गश्त करने के सख्त निर्देश दिए गए।",
        variables: [
          { key: "presentCount", labelHi: "हाज़िर मुलाज़िम", labelEn: "Present Count", type: "number", required: true, defaultValue: "18" },
          { key: "leaveCount", labelHi: "छुट्टी पर मुलाज़िम", labelEn: "On Leave", type: "number", required: true, defaultValue: "3" },
          { key: "sickCount", labelHi: "बीमार/अन्य", labelEn: "Sick / Other", type: "number", required: true, defaultValue: "1" },
        ],
        isDefault: true,
      },
    ],
  },
  {
    code: "SAFAI_THANA",
    category: "ROUTINE_ADMINISTRATION",
    nameEn: "Safai Thana & Hawalat Inspection",
    nameHi: "सफाई थाना व मुआयना हवालात",
    description: "Sanitation check, water/light arrangements in lockup, female barracks, office and Malkhana premises.",
    isEnabled: true,
    usedCount: 15,
    requiresOfficer: false,
    defaultTemplates: [
      {
        id: "tmpl_safai_hi",
        typeCode: "SAFAI_THANA",
        title: "सफाई थाना व मुआयना हवालात (हिंदी)",
        titleHi: "सफाई थाना",
        language: "hi",
        subjectTemplate: "सफाई थाना, मुआयना हवालात व बैरक मुलाज़मान",
        bodyTemplate:
          "थाना परिसर, मालखाना, हवालात, बैरक व कार्यालय की व्यापक सफाई करवाई गई। हवालात में पानी, बिजली व पंखे सुचारू पाए गए। प्राथमिक चिकित्सा किट (First Aid) उपलब्ध पाई गई। कोई आपत्तिजनक वस्तु हवालात में नहीं पाई गई।",
        variables: [],
        isDefault: true,
      },
    ],
  },
  {
    code: "RAVANGI_OFFICER",
    category: "DUTY_MOVEMENT",
    nameEn: "Ravangi / Departure (Investigation/Raid)",
    nameHi: "रवानगी मुलाज़मान (तफ्तीश / गश्त / रेड)",
    description: "Departure of Investigating Officer / staff mentioning specific reason, case/complaint reference, destination, arms and vehicle.",
    isEnabled: true,
    usedCount: 45,
    requiresOfficer: true,
    requiresVehicle: true,
    requiresCaseReference: true,
    defaultTemplates: [
      {
        id: "tmpl_ravangi_hi",
        typeCode: "RAVANGI_OFFICER",
        title: "रवानगी मुलाज़िम बराए तफ्तीश (हिंदी)",
        titleHi: "रवानगी तफ्तीश",
        language: "hi",
        subjectTemplate: "रवानगी {{officerRank}} {{officerName}} बराए तफ्तीश {{caseRef}} बामुकाम {{destination}}",
        bodyTemplate:
          "बवक्त {{departureTime}}, {{officerRank}} {{officerName}} (बेल्ट नं: {{officerBelt}}) हमराह मुलाज़मान {{accompanyingStaff}} बराए तफ्तीश/जांच दरख्वास्त/मुकदमा नंबर {{caseRef}} बामुकाम {{destination}} रवाना हुए। रवानगी बा-सवारी {{vehicleDetail}} अमल में लाई गई। हथियार असलहा सरकारी {{weaponsIssued}} साथ लिया गया। डायरी रवानगी दर्ज रजिस्टर की गई।",
        variables: [
          { key: "departureTime", labelHi: "रवानगी समय", labelEn: "Departure Time", type: "time", required: true, autoFillSource: "nowTime" },
          { key: "officerRank", labelHi: "अधिकारी का पद", labelEn: "Officer Rank", type: "text", required: true, autoFillSource: "selectedOfficer" },
          { key: "officerName", labelHi: "अधिकारी का नाम", labelEn: "Officer Name", type: "text", required: true, autoFillSource: "selectedOfficer" },
          { key: "officerBelt", labelHi: "बेल्ट नंबर", labelEn: "Belt Number", type: "text", required: true, autoFillSource: "selectedOfficer" },
          { key: "accompanyingStaff", labelHi: "हमराह मुलाज़मान", labelEn: "Accompanying Staff", type: "text", required: false, defaultValue: "HC Sandeep No. 412" },
          { key: "caseRef", labelHi: "मुकदमा/दरख्वास्त संदर्भ", labelEn: "Case / Complaint Ref", type: "text", required: true, defaultValue: "CMP-2026-00482" },
          { key: "destination", labelHi: "गंतव्य स्थान / मौका", labelEn: "Destination / Spot", type: "text", required: true, defaultValue: "Sector 7, Urban Estate" },
          { key: "vehicleDetail", labelHi: "वाहन विवरण", labelEn: "Vehicle Details", type: "text", required: false, defaultValue: "सरकारी जिप्सी HR-07-G-1102" },
          { key: "weaponsIssued", labelHi: "सरकारी हथियार", labelEn: "Weapons Carried", type: "text", required: false, defaultValue: "9mm Pistol मय 10 राउंड" },
        ],
        isDefault: true,
      },
    ],
  },
  {
    code: "WAPSI_OFFICER",
    category: "DUTY_MOVEMENT",
    nameEn: "Wapsi / Return (After Investigation/Patrol)",
    nameHi: "वापसी मुलाज़मान (बाद तफ्तीश / गश्त)",
    description: "Return of police personnel to police station after completing investigation, summons service or patrol, depositing case files & arms.",
    isEnabled: true,
    usedCount: 38,
    requiresOfficer: true,
    defaultTemplates: [
      {
        id: "tmpl_wapsi_hi",
        typeCode: "WAPSI_OFFICER",
        title: "वापसी मुलाज़िम बाद तफ्तीश (हिंदी)",
        titleHi: "वापसी तफ्तीश",
        language: "hi",
        subjectTemplate: "वापसी {{officerRank}} {{officerName}} बाद तफ्तीश मौका {{destination}}",
        bodyTemplate:
          "बवक्त {{arrivalTime}}, {{officerRank}} {{officerName}} (बेल्ट नं: {{officerBelt}}) हमराह स्टाफ बाद तफ्तीश/जांच मौका {{destination}} खैरियत से वापस थाना आए। जांच की विस्तृत कार्यवाही केस डायरी में कलमबद्ध की गई है। सरकारी असलहा व वाहन बिना किसी नुकसानी के सुरक्षित जमा करवा दिया गया है। रिपोर्ट वापसी दर्ज रोजनामचा की गई।",
        variables: [
          { key: "arrivalTime", labelHi: "वापसी समय", labelEn: "Arrival Time", type: "time", required: true, autoFillSource: "nowTime" },
          { key: "officerRank", labelHi: "अधिकारी का पद", labelEn: "Officer Rank", type: "text", required: true, autoFillSource: "selectedOfficer" },
          { key: "officerName", labelHi: "अधिकारी का नाम", labelEn: "Officer Name", type: "text", required: true, autoFillSource: "selectedOfficer" },
          { key: "officerBelt", labelHi: "बेल्ट नंबर", labelEn: "Belt Number", type: "text", required: true, autoFillSource: "selectedOfficer" },
          { key: "destination", labelHi: "स्थान जहां से वापसी हुई", labelEn: "Returned From", type: "text", required: true, defaultValue: "Sector 7, Kurukshetra" },
        ],
        isDefault: true,
      },
    ],
  },
  {
    code: "DUTY_ASSIGNMENT",
    category: "DUTY_MOVEMENT",
    nameEn: "Duty Assignment / Sentry Relief",
    nameHi: "तब्दीली पहरा व संतरी ड्यूटी (Sentry Relief)",
    description: "Handing over and taking over of sentry guard, lockup sentry, and wireless operator duties with arms tally.",
    isEnabled: true,
    usedCount: 29,
    requiresOfficer: true,
    defaultTemplates: [
      {
        id: "tmpl_duty_hi",
        typeCode: "DUTY_ASSIGNMENT",
        title: "तब्दीली पहरा संतरी (हिंदी)",
        titleHi: "संतरी तब्दीली",
        language: "hi",
        subjectTemplate: "तब्दीली पहरा संतरी थाना - {{relievedOfficer}} को {{relievingOfficer}} द्वारा बदला गया",
        bodyTemplate:
          "बवक्त {{shiftTime}}, संतरी ड्यूटी पर तैनात {{relievedOfficer}} (बेल्ट: {{relievedBelt}}) को अवधि समाप्त होने पर {{relievingOfficer}} (बेल्ट: {{relievingBelt}}) द्वारा बदला गया। सरकारी राइफल/हथियार संख्या {{weaponNo}} मय {{ammunitionCount}} राउंड और हवालात के बंदियों का प्रभार बा-दस्तूर दुरुस्त हालत में सौंप दिया गया। नया संतरी मुस्तैदी से ड्यूटी पर तैनात है।",
        variables: [
          { key: "shiftTime", labelHi: "तब्दीली समय", labelEn: "Shift Time", type: "time", required: true, autoFillSource: "nowTime" },
          { key: "relievedOfficer", labelHi: "भूतपूर्व संतरी", labelEn: "Relieved Officer", type: "text", required: true, defaultValue: "Constable Manoj Kumar" },
          { key: "relievedBelt", labelHi: "भूतपूर्व बेल्ट", labelEn: "Relieved Belt No", type: "text", required: true, defaultValue: "614/KKR" },
          { key: "relievingOfficer", labelHi: "नया संतरी", labelEn: "Relieving Officer", type: "text", required: true, defaultValue: "Constable Praveen Singh" },
          { key: "relievingBelt", labelHi: "नया बेल्ट", labelEn: "Relieving Belt No", type: "text", required: true, defaultValue: "902/KKR" },
          { key: "weaponNo", labelHi: "हथियार नंबर", labelEn: "Weapon No", type: "text", required: false, defaultValue: "SLR No. 154829" },
          { key: "ammunitionCount", labelHi: "कारतूस संख्या", labelEn: "Ammunition Count", type: "number", required: false, defaultValue: "20" },
        ],
        isDefault: true,
      },
    ],
  },
  {
    code: "FIR_REGISTRATION",
    category: "INVESTIGATION_PROCESS",
    nameEn: "FIR Registration Intimation",
    nameHi: "इत्तिला दर्ज एफ.आई.आर. (FIR Intimation)",
    description: "Recording registration of formal First Information Report under BNSS 173 and relevant penal sections.",
    isEnabled: true,
    usedCount: 20,
    requiresOfficer: true,
    requiresCaseReference: true,
    defaultTemplates: [
      {
        id: "tmpl_fir_hi",
        typeCode: "FIR_REGISTRATION",
        title: "इत्तिला दर्ज मुकदमा एफ.आई.आर. (हिंदी)",
        titleHi: "दर्ज एफ.आई.आर.",
        language: "hi",
        subjectTemplate: "दर्ज मुकदमा नंबर {{firNo}} ब-जुर्म {{sections}} थाना {{stationName}}",
        bodyTemplate:
          "बवक्त {{regTime}}, मुसम्मी {{complainantName}} की लिखित शिकायत पर अभियोग संख्या {{firNo}} धारा {{sections}} के अंतर्गत थाना हाज़ा में दर्ज रजिस्टर किया गया। मूल तहरीर व नकल एफआईआर तफ्तीश हेतु जांच अधिकारी {{ioName}} (बेल्ट: {{ioBelt}}) के हवाले की गई। विशेष रिपोर्ट (Special Report) इलाका मजिस्ट्रेट व उच्चाधिकारियों को डाक द्वारा भिजवाई जा रही है।",
        variables: [
          { key: "regTime", labelHi: "दर्ज समय", labelEn: "Registration Time", type: "time", required: true, autoFillSource: "nowTime" },
          { key: "firNo", labelHi: "एफआईआर नंबर", labelEn: "FIR Number", type: "text", required: true, defaultValue: "142/2026" },
          { key: "sections", labelHi: "कानूनी धाराएं (BNS / Special)", labelEn: "Sections of Law", type: "text", required: true, defaultValue: "Section 303(2), 317(2) BNS, 2023" },
          { key: "stationName", labelHi: "थाने का नाम", labelEn: "Police Station", type: "text", required: true, autoFillSource: "station" },
          { key: "complainantName", labelHi: "शिकायतकर्ता का नाम", labelEn: "Complainant Name", type: "text", required: true, defaultValue: "Rameshwar Dayal" },
          { key: "ioName", labelHi: "नियुक्त IO का नाम", labelEn: "Assigned IO Name", type: "text", required: true, defaultValue: "SI Vikram Singh" },
          { key: "ioBelt", labelHi: "IO बेल्ट नंबर", labelEn: "IO Belt No", type: "text", required: true, defaultValue: "742/KKR" },
        ],
        isDefault: true,
      },
    ],
  },
  {
    code: "COMPLAINT_INTAKE",
    category: "INVESTIGATION_PROCESS",
    nameEn: "Complaint Received / Disposal",
    nameHi: "प्राप्ति / निपटान शिकायत दरख्वास्त (PPR 22.48)",
    description: "Official intake of citizen grievance petition, CM Window, or formal enquiry completion log.",
    isEnabled: true,
    usedCount: 54,
    requiresOfficer: true,
    requiresCaseReference: true,
    defaultTemplates: [
      {
        id: "tmpl_comp_hi",
        typeCode: "COMPLAINT_INTAKE",
        title: "प्राप्ति दरख्वास्त नागरिक (हिंदी)",
        titleHi: "प्राप्ति शिकायत",
        language: "hi",
        subjectTemplate: "प्राप्ति दरख्वास्त शिकायत क्रमांक {{complaintNo}} मनजानिब {{complainantName}}",
        bodyTemplate:
          "बवक्त {{receiptTime}}, मुसम्मी {{complainantName}} (मो: {{phone}}) द्वारा थाना में उपस्थित होकर लिखित दरख्वास्त पेश की गई, जिसका विषय '{{subject}}' है। दरख्वास्त को केंद्रीय शिकायत रजिस्टर में दर्ज करके जांच अधिकारी {{eoName}} (पद: {{eoRank}}) को धारा 173(3) BNSS के तहत 14 दिन में प्रारंभिक जांच हेतु सौंपा गया। पावती रसीद शिकायतकर्ता को जारी की गई।",
        variables: [
          { key: "receiptTime", labelHi: "प्राप्ति समय", labelEn: "Intake Time", type: "time", required: true, autoFillSource: "nowTime" },
          { key: "complaintNo", labelHi: "शिकायत नंबर", labelEn: "Complaint No", type: "text", required: true, defaultValue: "HAR-KKR-2026-CMP-00482" },
          { key: "complainantName", labelHi: "शिकायतकर्ता", labelEn: "Complainant", type: "text", required: true, defaultValue: "Suraj Bhan" },
          { key: "phone", labelHi: "मोबाइल नंबर", labelEn: "Mobile No", type: "text", required: false, defaultValue: "9812039482" },
          { key: "subject", labelHi: "शिकायत का विषय", labelEn: "Subject", type: "text", required: true, defaultValue: "बाबत धोखाधड़ी व गबन बाबत बैंक खाता" },
          { key: "eoName", labelHi: "जांच अधिकारी", labelEn: "Enquiry Officer", type: "text", required: true, defaultValue: "SI Vikram Singh" },
          { key: "eoRank", labelHi: "EO का पद", labelEn: "EO Rank", type: "text", required: true, defaultValue: "Sub-Inspector" },
        ],
        isDefault: true,
      },
    ],
  },
  {
    code: "ARREST_BANDI",
    category: "LAW_AND_ORDER",
    nameEn: "Arrest / Bandi Hawalat",
    nameHi: "गिरफ्तारी व दाखिला हवालात (Arrest Entry)",
    description: "Apprehension of accused, medical examination at civil hospital, memo of arrest, intimation to kin and lockup admission.",
    isEnabled: true,
    usedCount: 16,
    requiresOfficer: true,
    requiresCaseReference: true,
    defaultTemplates: [
      {
        id: "tmpl_arrest_hi",
        typeCode: "ARREST_BANDI",
        title: "दाखिला हवालात मुलजिम (हिंदी)",
        titleHi: "गिरफ्तारी व दाखिला",
        language: "hi",
        subjectTemplate: "गिरफ्तारी व दाखिला हवालात मुलजिम {{accusedName}} मुकदमा नं {{firNo}}",
        bodyTemplate:
          "मुकदमा नंबर {{firNo}} धारा {{sections}} में नामजद आरोपी {{accusedName}} वल्द {{fatherName}} साकिन {{address}} को बवक्त {{arrestTime}} गिरफ्तार किया गया। गिरफ्तारी मेमो तैयार किया गया व अभियुक्त के परिजनों {{relativeName}} को गिरफ्तारी की कानूनी सूचना दी गई। अभियुक्त का नागरिक अस्पताल से मेडिकल परीक्षण करवाया गया। अभियुक्त की जामा तलाशी ली गई व उसे हवालात थाना में सुरक्षित बंद किया गया।",
        variables: [
          { key: "arrestTime", labelHi: "गिरफ्तारी समय", labelEn: "Arrest Time", type: "time", required: true, autoFillSource: "nowTime" },
          { key: "firNo", labelHi: "मुकदमा नंबर", labelEn: "FIR No", type: "text", required: true, defaultValue: "142/2026" },
          { key: "sections", labelHi: "धाराएं", labelEn: "Sections", type: "text", required: true, defaultValue: "Section 303(2) BNS" },
          { key: "accusedName", labelHi: "अभियुक्त का नाम", labelEn: "Accused Name", type: "text", required: true, defaultValue: "Sunil Kumar @ Sonu" },
          { key: "fatherName", labelHi: "पिता का नाम", labelEn: "Father's Name", type: "text", required: true, defaultValue: "Ram Lal" },
          { key: "address", labelHi: "पता", labelEn: "Address", type: "text", required: true, defaultValue: "VPO Pipli, Kurukshetra" },
          { key: "relativeName", labelHi: "सूचित परिजन", labelEn: "Informed Relative", type: "text", required: true, defaultValue: "Bhai Anil Kumar (9812000000)" },
        ],
        isDefault: true,
      },
    ],
  },
  {
    code: "RELEASE_HAWALAT",
    category: "LAW_AND_ORDER",
    nameEn: "Release / Hawalat Clearance",
    nameHi: "रिहाई मुल्जिम / ज़मानत (Discharge/Bail)",
    description: "Release of accused on station bail (Section 479 BNSS), court bail bond verification, or Section 35(3) notice undertaking.",
    isEnabled: true,
    usedCount: 9,
    requiresOfficer: true,
    requiresCaseReference: true,
    defaultTemplates: [
      {
        id: "tmpl_release_hi",
        typeCode: "RELEASE_HAWALAT",
        title: "रिहाई मुल्जिम ब-ज़मानत (हिंदी)",
        titleHi: "रिहाई मुल्जिम",
        language: "hi",
        subjectTemplate: "रिहाई मुलजिम {{accusedName}} ब-मुकदमा {{firNo}} ब-ज़मानत थाना/अदालत",
        bodyTemplate:
          "मुकदमा नंबर {{firNo}} में हवालात बंद आरोपी {{accusedName}} को माननीय अदालत/SHO महोदय के आदेशानुसार जमानत मुचलका बा-रकम रु {{bailAmount}} मय जामिन {{suretyName}} तस्दीक होने पर हवालात से रिहा किया गया। अभियुक्त का निजी सामान जामा तलाशी रजिस्टर से मिलान करके सही सलामत सुपुर्द किया गया।",
        variables: [
          { key: "accusedName", labelHi: "अभियुक्त का नाम", labelEn: "Accused Name", type: "text", required: true, defaultValue: "Sunil Kumar @ Sonu" },
          { key: "firNo", labelHi: "मुकदमा नंबर", labelEn: "FIR No", type: "text", required: true, defaultValue: "142/2026" },
          { key: "bailAmount", labelHi: "ज़मानत राशि", labelEn: "Bail Amount (Rs)", type: "text", required: true, defaultValue: "25,000/-" },
          { key: "suretyName", labelHi: "ज़ामिनदार का नाम", labelEn: "Surety Name", type: "text", required: true, defaultValue: "Karamjit Singh S/O Harpal Singh" },
        ],
        isDefault: true,
      },
    ],
  },
  {
    code: "CASE_PROPERTY_DEPOSIT",
    category: "PROPERTY_MALKHANA",
    nameEn: "Case Property Deposit / Release (Malkhana)",
    nameHi: "मुद्देमाल मालखाना जमा / निकासी (Mudaddamal)",
    description: "Entry and withdrawal of case exhibits, seized currency, weapons, vehicles into Register No. XIX (Malkhana).",
    isEnabled: true,
    usedCount: 24,
    requiresOfficer: true,
    requiresCaseReference: true,
    defaultTemplates: [
      {
        id: "tmpl_malkhana_hi",
        typeCode: "CASE_PROPERTY_DEPOSIT",
        title: "दाखिला माल मुकदमा मालखाना (हिंदी)",
        titleHi: "मालखाना जमा",
        language: "hi",
        subjectTemplate: "दाखिला माल मुकदमा नंबर {{firNo}} मालखाना रजिस्टर नं 19 मद {{malkhanaEntryNo}}",
        bodyTemplate:
          "जांच अधिकारी {{ioName}} द्वारा मुकदमा नंबर {{firNo}} में बरामद किया गया मुद्देमाल: '{{propertyDescription}}' मुहरबंद हालत में थाना मालखाना में दाखिल कराया गया। मालखाना मोहर्रिर द्वारा रजिस्टर नंबर 19 में मद नंबर {{malkhanaEntryNo}} पर दर्ज करके सुरक्षित मालखाना स्ट्रांग रूम में रखवाया गया।",
        variables: [
          { key: "ioName", labelHi: "जमाकर्ता IO", labelEn: "Depositing IO", type: "text", required: true, defaultValue: "ASI Ramesh Chander" },
          { key: "firNo", labelHi: "मुकदमा नंबर", labelEn: "FIR No", type: "text", required: true, defaultValue: "142/2026" },
          { key: "propertyDescription", labelHi: "मुद्देमाल का विवरण", labelEn: "Property Description", type: "text", required: true, defaultValue: "1 अदद लैपटॉप लेनोवो, 1 अदद मोबाइल ओप्पो व नकदी रु 14,500/-" },
          { key: "malkhanaEntryNo", labelHi: "मालखाना मद नंबर (Reg XIX)", labelEn: "Malkhana Entry No", type: "text", required: true, defaultValue: "41/19" },
        ],
        isDefault: true,
      },
    ],
  },
  {
    code: "SEIZURE_FARD",
    category: "PROPERTY_MALKHANA",
    nameEn: "Seizure / Fard Zabti",
    nameHi: "बरामदगी व ज़ब्ती माल (Fard Zabti)",
    description: "Execution of seizure memo for stolen items, weapons, illicit liquor, contraband or disputed property.",
    isEnabled: true,
    usedCount: 18,
    requiresOfficer: true,
    requiresCaseReference: true,
    defaultTemplates: [
      {
        id: "tmpl_seizure_hi",
        typeCode: "SEIZURE_FARD",
        title: "फर्द ज़ब्ती व बरामदगी (हिंदी)",
        titleHi: "फर्द ज़ब्ती",
        language: "hi",
        subjectTemplate: "बरामदगी माल व फर्द ज़ब्ती मुकदमा नंबर {{firNo}} ब-जुर्म {{sections}}",
        bodyTemplate:
          "तफ्तीश के दौरान आरोपी {{accusedName}} के कब्जे/निशानदेही से स्थान {{seizurePlace}} से '{{itemSeized}}' बरामद करके फर्द ज़ब्ती तैयार की गई। फर्द पर गवाहान {{witnesses}} के हस्ताक्षर करवाए गए। माल को मुहरबंद करके पुलिस कब्जे में लिया गया।",
        variables: [
          { key: "firNo", labelHi: "मुकदमा नंबर", labelEn: "FIR No", type: "text", required: true, defaultValue: "142/2026" },
          { key: "sections", labelHi: "धाराएं", labelEn: "Sections", type: "text", required: true, defaultValue: "Section 303(2) BNS" },
          { key: "accusedName", labelHi: "अभियुक्त", labelEn: "Accused", type: "text", required: true, defaultValue: "Sunil Kumar" },
          { key: "seizurePlace", labelHi: "बरामदगी स्थान", labelEn: "Seizure Place", type: "text", required: true, defaultValue: "झाड़ियां नजदीक रेलवे पुल, थानेसर" },
          { key: "itemSeized", labelHi: "बरामद वस्तु", labelEn: "Seized Item", type: "text", required: true, defaultValue: "चोरीशुदा मोटरसाइकिल स्पलेंडर HR-07-K-4819" },
          { key: "witnesses", labelHi: "गवाहान", labelEn: "Witnesses", type: "text", required: false, defaultValue: "HC Sandeep No. 412 व स्वतंत्र गवाह श्री मोहन लाल" },
        ],
        isDefault: true,
      },
    ],
  },
  {
    code: "FSL_DISPATCH_RECEIPT",
    category: "INVESTIGATION_PROCESS",
    nameEn: "FSL Dispatch / Receipt",
    nameHi: "रवानगी / प्राप्ति पार्सल एफ.एस.एल. मधुबन (FSL Parcel)",
    description: "Dispatch of blood, viscera, ballistics, cyber forensic exhibits to Forensic Science Laboratory, Madhuban and receipt of FSL reports.",
    isEnabled: true,
    usedCount: 11,
    requiresOfficer: true,
    requiresCaseReference: true,
    defaultTemplates: [
      {
        id: "tmpl_fsl_hi",
        typeCode: "FSL_DISPATCH_RECEIPT",
        title: "रवानगी पार्सल एफ.एस.एल. मधुबन (हिंदी)",
        titleHi: "रवानगी FSL",
        language: "hi",
        subjectTemplate: "रवानगी पार्सल एफ.एस.एल. मुकदमा नंबर {{firNo}} हमराह {{officerName}}",
        bodyTemplate:
          "मुकदमा नंबर {{firNo}} में जब्तशुदा {{parcelCount}} अदद मुहरबंद पार्सल जांच हेतु राज्य फॉरेंसिक साइंस प्रयोगशाला (FSL) मधुबन (करनाल) भिजवाने हेतु स्पेशल वाहक {{officerName}} (बेल्ट: {{officerBelt}}) के सुपुर्द किए गए। रोड सर्टिफिकेट (RC) नंबर {{rcNumber}} जारी किया गया। मालखाना मुहर सही पाई गई।",
        variables: [
          { key: "firNo", labelHi: "मुकदमा नंबर", labelEn: "FIR No", type: "text", required: true, defaultValue: "142/2026" },
          { key: "parcelCount", labelHi: "पार्सल संख्या", labelEn: "Parcel Count", type: "number", required: true, defaultValue: "3" },
          { key: "officerName", labelHi: "वाहक का नाम", labelEn: "Bearer Officer", type: "text", required: true, defaultValue: "Constable Vikas Kumar" },
          { key: "officerBelt", labelHi: "बेल्ट नंबर", labelEn: "Belt No", type: "text", required: true, defaultValue: "782/KKR" },
          { key: "rcNumber", labelHi: "रोड सर्टिफिकेट (RC) नंबर", labelEn: "RC Number", type: "text", required: true, defaultValue: "118/RC/2026" },
        ],
        isDefault: true,
      },
    ],
  },
  {
    code: "COURT_PRODUCTION",
    category: "COURT_DOCUMENTATION",
    nameEn: "Court Production / Return",
    nameHi: "पेशी अदालत व वापसी (Court Production)",
    description: "Escort of arrested persons to judicial magistrate court for remand, bail, or judicial custody, and return of escort party.",
    isEnabled: true,
    usedCount: 19,
    requiresOfficer: true,
    requiresCaseReference: true,
    defaultTemplates: [
      {
        id: "tmpl_court_hi",
        typeCode: "COURT_PRODUCTION",
        title: "रवानगी पेशी अदालत (हिंदी)",
        titleHi: "पेशी अदालत",
        language: "hi",
        subjectTemplate: "रवानगी पेशी अदालत मुल्जिम {{accusedName}} मुकदमा नं {{firNo}}",
        bodyTemplate:
          "मुकदमा नंबर {{firNo}} में गिरफ्तारशुदा आरोपी {{accusedName}} को माननीय अदालत श्रीमान इलाका मजिस्ट्रेट (JMFC) कुरुक्षेत्र में पेशी व रिमांड हेतु पुलिस गारद हमराह {{escortIncharge}} (बेल्ट: {{beltNo}}) मय मुलाज़मान रवाना किया गया। आरोपी को हथकड़ी व सुरक्षा नियमों का पालन करते हुए ले जाया गया।",
        variables: [
          { key: "firNo", labelHi: "मुकदमा नंबर", labelEn: "FIR No", type: "text", required: true, defaultValue: "142/2026" },
          { key: "accusedName", labelHi: "अभियुक्त का नाम", labelEn: "Accused Name", type: "text", required: true, defaultValue: "Sunil Kumar @ Sonu" },
          { key: "escortIncharge", labelHi: "गारद इंचार्ज", labelEn: "Escort Incharge", type: "text", required: true, defaultValue: "HC Rajesh Kumar" },
          { key: "beltNo", labelHi: "बेल्ट नंबर", labelEn: "Belt Number", type: "text", required: true, defaultValue: "551/KKR" },
        ],
        isDefault: true,
      },
    ],
  },
  {
    code: "VEHICLE_MOVEMENT",
    category: "DUTY_MOVEMENT",
    nameEn: "Vehicle Movement (Government Logistic)",
    nameHi: "रवानगी / आमद सरकारी गाड़ी (Government Vehicle)",
    description: "Departure and arrival of police patrol vehicle, PCR van, ERV Dial 112, stating driver, speedometer reading and fuel log.",
    isEnabled: true,
    usedCount: 31,
    requiresOfficer: true,
    requiresVehicle: true,
    defaultTemplates: [
      {
        id: "tmpl_vehicle_hi",
        typeCode: "VEHICLE_MOVEMENT",
        title: "रवानगी सरकारी गाड़ी (हिंदी)",
        titleHi: "रवानगी वाहन",
        language: "hi",
        subjectTemplate: "रवानगी सरकारी वाहन {{vehicleNumber}} चालक {{driverName}} बा-मकसद {{purpose}}",
        bodyTemplate:
          "सरकारी वाहन संख्या {{vehicleNumber}} चालक {{driverName}} (बेल्ट: {{beltNo}}) बा-मकसद {{purpose}} रवाना किया गया। रवानगी के वक्त स्पीडोमीटर मीटर रीडिंग: {{meterReading}} किमी पाई गई। वाहन में ईंधन पर्याप्त है। वाहन लॉगबुक में प्रविष्टि कर दी गई है।",
        variables: [
          { key: "vehicleNumber", labelHi: "वाहन नंबर", labelEn: "Vehicle Reg No", type: "text", required: true, defaultValue: "HR-07-G-1102 (Bolero)" },
          { key: "driverName", labelHi: "चालक का नाम", labelEn: "Driver Name", type: "text", required: true, defaultValue: "EHC Kuldeep Singh" },
          { key: "beltNo", labelHi: "बेल्ट नंबर", labelEn: "Belt Number", type: "text", required: true, defaultValue: "329/KKR" },
          { key: "purpose", labelHi: "उद्देश्य", labelEn: "Purpose", type: "text", required: true, defaultValue: "पेट्रोलिंग व क्राइम कंट्रोल बीट नंबर 2" },
          { key: "meterReading", labelHi: "मीटर रीडिंग (किमी)", labelEn: "Meter Reading (km)", type: "text", required: true, defaultValue: "48,920 KM" },
        ],
        isDefault: true,
      },
    ],
  },
  {
    code: "DOCUMENT_MOVEMENT",
    category: "COURT_DOCUMENTATION",
    nameEn: "Document Received / Sent (Dak/Summons/Warrants)",
    nameHi: "डाक आमद व रवानगी (समन / वारंट / डाक)",
    description: "Receipt and delivery of summons, warrants, high court directions, SP Office correspondence, and process serving.",
    isEnabled: true,
    usedCount: 27,
    requiresOfficer: true,
    defaultTemplates: [
      {
        id: "tmpl_doc_hi",
        typeCode: "DOCUMENT_MOVEMENT",
        title: "प्राप्ति / रवानगी समन व वारंट (हिंदी)",
        titleHi: "डाक व समन",
        language: "hi",
        subjectTemplate: "प्राप्ति डाक/समन संख्या {{processNo}} अदालत {{courtName}}",
        bodyTemplate:
          "माननीय अदालत {{courtName}} से कुल {{docCount}} समन/वारंट प्राप्त हुए, जिनका विवरण समन रजिस्टर में दर्ज किया गया। तामील हेतु संबंधित बीट कांस्टेबल {{officerName}} (बेल्ट: {{beltNo}}) के सुपुर्द किए गए, जिन्हें निश्चित तिथि {{dueDate}} से पूर्व तामील कराकर रिपोर्ट पेश करने के निर्देश दिए गए।",
        variables: [
          { key: "courtName", labelHi: "अदालत का नाम", labelEn: "Court Name", type: "text", required: true, defaultValue: "Court of CJM Kurukshetra" },
          { key: "processNo", labelHi: "समन/वारंट क्रमांक", labelEn: "Process / Summons No", type: "text", required: true, defaultValue: "Summons No. 842-845" },
          { key: "docCount", labelHi: "दस्तावेज़ संख्या", labelEn: "Document Count", type: "number", required: true, defaultValue: "4" },
          { key: "officerName", labelHi: "तामीलकर्ता मुलाज़िम", labelEn: "Process Server", type: "text", required: true, defaultValue: "Constable Praveen Kumar" },
          { key: "beltNo", labelHi: "बेल्ट नंबर", labelEn: "Belt Number", type: "text", required: true, defaultValue: "902/KKR" },
          { key: "dueDate", labelHi: "पेशी/तामील अंतिम तिथि", labelEn: "Due Date", type: "date", required: true, defaultValue: "2026-10-15" },
        ],
        isDefault: true,
      },
    ],
  },
  {
    code: "BEAT_PATROLLING",
    category: "LAW_AND_ORDER",
    nameEn: "Beat / Patrolling & Naka Checking",
    nameHi: "गश्त व नाकाबंदी बीट एरिया (Beat Patrolling)",
    description: "Foot patrol, motorcycle patrol, night domination and surprise vehicle checking on major intersections.",
    isEnabled: true,
    usedCount: 36,
    requiresOfficer: true,
    defaultTemplates: [
      {
        id: "tmpl_beat_hi",
        typeCode: "BEAT_PATROLLING",
        title: "रवानगी गश्त व नाकाबंदी बीट (हिंदी)",
        titleHi: "गश्त बीट",
        language: "hi",
        subjectTemplate: "रवानगी मुलाज़मान बराए गश्त, नाकाबंदी व क्राइम कंट्रोल बीट {{beatName}}",
        bodyTemplate:
          "बवक्त {{patrolTime}}, {{inchargeName}} (बेल्ट: {{inchargeBelt}}) हमराह मुलाज़मान बीट एरिया {{beatName}} में पैदल व वाहन गश्त, नाकाबंदी एवं संदिग्ध व्यक्तियों/वाहनों की चेकिंग हेतु रवाना हुए। गश्त के दौरान बैंकों, एटीएम, सर्राफा बाजार व भीड़-भाड़ वाले क्षेत्रों पर विशेष सतर्कता बरतने के निर्देश दिए गए।",
        variables: [
          { key: "patrolTime", labelHi: "गश्त समय", labelEn: "Patrol Time", type: "time", required: true, autoFillSource: "nowTime" },
          { key: "beatName", labelHi: "बीट क्षेत्र का नाम", labelEn: "Beat Name", type: "text", required: true, defaultValue: "Beat No. 3 (Railway Station & Old Bus Stand)" },
          { key: "inchargeName", labelHi: "गश्त इंचार्ज", labelEn: "Patrol Incharge", type: "text", required: true, defaultValue: "ASI Ramesh Chander" },
          { key: "inchargeBelt", labelHi: "बेल्ट नंबर", labelEn: "Belt Number", type: "text", required: true, defaultValue: "419/KKR" },
        ],
        isDefault: true,
      },
    ],
  },
  {
    code: "SUPERVISORY_CHECKING",
    category: "LAW_AND_ORDER",
    nameEn: "Checking / Supervisory Visit",
    nameHi: "पड़ताल व मुआयना अफ़सरान (Supervisory Inspection)",
    description: "Inspection visit by Superintendent of Police (SP), DSP (Sub-Division), or SHO checking registers, hawalat, sentry alertness and staff.",
    isEnabled: true,
    usedCount: 17,
    requiresOfficer: true,
    defaultTemplates: [
      {
        id: "tmpl_supervisory_hi",
        typeCode: "SUPERVISORY_CHECKING",
        title: "मुआयना व पड़ताल उच्चाधिकारी (हिंदी)",
        titleHi: "पड़ताल अफ़सरान",
        language: "hi",
        subjectTemplate: "आकस्मिक मुआयना थाना हाज़ा मनजानिब {{officerRank}} {{officerName}}",
        bodyTemplate:
          "बवक्त {{visitTime}}, {{officerRank}} महोदय {{officerName}} द्वारा थाना हाज़ा का आकस्मिक निरीक्षण किया गया। संतरी पहरा मुस्तैद पाया गया। हवालात, शस्त्रागार, मालखाना व रोजनामचा रजिस्टरों का निरीक्षण किया गया। साफ-सफाई व रिकॉर्ड का रख-रखाव संतोषजनक पाया गया। लंबित शिकायतों व एनडीपीएस/सड़क दुर्घटना मामलों के त्वरित निस्तारण के निर्देश दिए गए।",
        variables: [
          { key: "visitTime", labelHi: "निरीक्षण समय", labelEn: "Inspection Time", type: "time", required: true, autoFillSource: "nowTime" },
          { key: "officerRank", labelHi: "उच्चाधिकारी का पद", labelEn: "Rank", type: "text", required: true, defaultValue: "DSP (Sub-Division)" },
          { key: "officerName", labelHi: "अधिकारी का नाम", labelEn: "Officer Name", type: "text", required: true, defaultValue: "Sh. Ram Niwas, HPS" },
        ],
        isDefault: true,
      },
    ],
  },
  {
    code: "INFORMATION_RECEIVED",
    category: "LAW_AND_ORDER",
    nameEn: "Information Received / Passed (Wireless/Control Room)",
    nameHi: "इत्तिला खूफिया / टेलीफोनिक संदेश (Information Log)",
    description: "Receipt of flash wireless message, Dial 112 event dispatch, VIP movement notification, or accident intimation.",
    isEnabled: true,
    usedCount: 42,
    requiresOfficer: false,
    defaultTemplates: [
      {
        id: "tmpl_info_hi",
        typeCode: "INFORMATION_RECEIVED",
        title: "इत्तिला टेलीफोनिक / कंट्रोल रूम (हिंदी)",
        titleHi: "इत्तिला संदेश",
        language: "hi",
        subjectTemplate: "प्राप्ति वायरलेस/कंट्रोल रूम संदेश बाबत {{infoTopic}}",
        bodyTemplate:
          "बवक्त {{msgTime}}, जिला पुलिस कंट्रोल रूम / डायल 112 से टेलीफोनिक संदेश प्राप्त हुआ कि '{{msgDetails}}'। सूचना पाकर तुरंत ईआरवी / संबंधित बीट अधिकारी {{assignedOfficer}} को मौके पर तुरंत पहुंचकर त्वरित कानूनी कार्यवाही करने हेतु वायरलेस संदेश द्वारा निर्देशित किया गया।",
        variables: [
          { key: "msgTime", labelHi: "प्राप्ति समय", labelEn: "Message Time", type: "time", required: true, autoFillSource: "nowTime" },
          { key: "infoTopic", labelHi: "सूचना का विषय", labelEn: "Topic", type: "text", required: true, defaultValue: "सड़क दुर्घटना नजदीक उमरी चौक" },
          { key: "msgDetails", labelHi: "विस्तृत सूचना", labelEn: "Message Details", type: "text", required: true, defaultValue: "एक कार व मोटरसाइकिल की टक्कर हुई है, जिसमें दो व्यक्ति घायल हुए हैं, एंबुलेंस व पुलिस की आवश्यकता है।" },
          { key: "assignedOfficer", labelHi: "मौके पर भेजा गया अधिकारी/वाहन", labelEn: "Dispatched Officer/ERV", type: "text", required: true, defaultValue: "ERV Dial 112 No. 0422 व ASI Surender Pal" },
        ],
        isDefault: true,
      },
    ],
  },
  {
    code: "OTHER_MISCELLANEOUS",
    category: "MISCELLANEOUS",
    nameEn: "Other Miscellaneous Occurrence",
    nameHi: "विविध घटना / अन्य रोजनामचा (Miscellaneous)",
    description: "Any other official police station event, lost and found article, weather damage, electricity outage or general entry.",
    isEnabled: true,
    usedCount: 25,
    requiresOfficer: false,
    defaultTemplates: [
      {
        id: "tmpl_misc_hi",
        typeCode: "OTHER_MISCELLANEOUS",
        title: "विविध रोजनामचा प्रविष्टि (हिंदी)",
        titleHi: "विविध घटना",
        language: "hi",
        subjectTemplate: "रपट रोजनामचा आम बाबत {{subject}}",
        bodyTemplate:
          "बवक्त {{entryTime}}, थाना हाज़ा में यह प्रविष्टि दर्ज की जाती है कि {{description}}। इस संबंध में आवश्यक कानूनी व विभागीय कार्यवाही अमल में लाई जा रही है।",
        variables: [
          { key: "entryTime", labelHi: "समय", labelEn: "Time", type: "time", required: true, autoFillSource: "nowTime" },
          { key: "subject", labelHi: "विषय", labelEn: "Subject", type: "text", required: true, defaultValue: "लापता दस्तावेज/सामान बाबत सूचना" },
          { key: "description", labelHi: "विस्तृत विवरण", labelEn: "Description", type: "text", required: true, defaultValue: "प्रार्थी द्वारा अपने गुमशुदा आधार कार्ड व ड्राइविंग लाइसेंस बाबत सूचना दर्ज करवाई गई।" },
        ],
        isDefault: true,
      },
    ],
  },
];
