import { GDEntryTypeConfig, GDTemplate } from "@/types/generalDiary";

export const INITIAL_GD_TYPES: GDEntryTypeConfig[] = [
  {
    code: "AAGAZ_ROZNAMCHA",
    category: "ROUTINE_ADMINISTRATION",
    nameEn: "Opening (Aagaz)",
    nameHi: "Opening (Aagaz)",
    description: "Daily formal commencement of General Diary at 12:00 AM / 08:00 AM with armory, lockup, cash chest, and sentry verification under PPR 22.48.",
    isEnabled: true,
    usedCount: 14,
    requiresOfficer: true,
    defaultTemplates: [
      {
        id: "tmpl_aagaz_en",
        typeCode: "AAGAZ_ROZNAMCHA",
        title: "Daily Commencement of General Diary",
        titleHi: "Daily Opening of Diary",
        language: "en",
        subjectTemplate: "Aagaz - Daily Opening of General Diary",
        bodyTemplate:
          "At 12:00 AM, the General Diary was formally opened in accordance with Punjab Police Rule 22.48. Sentry relief and lockup inspection conducted. Current lockup is empty and secure. Station armory, weapon registers, and cash chest verified. Sentry guard and MHC charge assumed. All station affairs reported in order.",
        variables: [
          { key: "lockupCount", labelHi: "Lockup Count", labelEn: "Lockup Count", type: "number", required: true, defaultValue: "0" },
          { key: "officerName", labelHi: "Officer Name", labelEn: "Officer Name", type: "text", required: true, autoFillSource: "selectedOfficer" },
        ],
        isDefault: true,
      },
    ],
  },
  {
    code: "BANDI_ROZNAMCHA",
    category: "ROUTINE_ADMINISTRATION",
    nameEn: "Closing (Bandi / Day-Close)",
    nameHi: "Closing (Bandi)",
    description: "24-hour formal closure and locking of General Diary under PPR 22.49.",
    isEnabled: true,
    usedCount: 12,
    requiresOfficer: true,
    defaultTemplates: [
      {
        id: "tmpl_bandi_en",
        typeCode: "BANDI_ROZNAMCHA",
        title: "24-Hour Closure of General Diary",
        titleHi: "Closing of Diary",
        language: "en",
        subjectTemplate: "Bandi - 24-Hour Closure of General Diary",
        bodyTemplate:
          "At 11:59 PM, the General Diary for the 24-hour cycle was formally closed and locked. All daily entries verified and recorded. Lockup secure and weapons accounted for. Register closed under PPR 22.49.",
        variables: [
          { key: "totalEntries", labelHi: "Total Entries", labelEn: "Total Entries", type: "number", required: true, defaultValue: "15" },
        ],
        isDefault: true,
      },
    ],
  },
  {
    code: "STAFF_GINTI",
    category: "ROUTINE_ADMINISTRATION",
    nameEn: "Roll Call (Ginti Staff)",
    nameHi: "Roll Call (Ginti)",
    description: "Daily morning roll call and staff parade, present strength, leave status, and duty briefing.",
    isEnabled: true,
    usedCount: 22,
    requiresOfficer: true,
    defaultTemplates: [
      {
        id: "tmpl_ginti_en",
        typeCode: "STAFF_GINTI",
        title: "Daily Staff Roll Call & Parade",
        titleHi: "Roll Call",
        language: "en",
        subjectTemplate: "Ginti - Daily Staff Roll Call & Parade",
        bodyTemplate:
          "At 08:00 AM, morning roll call and staff count conducted. 18 personnel present on parade, 2 on sanctioned leave, 1 on court duty. Personnel briefed on supervisory directives, law & order vigilance, and duty assignments.",
        variables: [
          { key: "presentCount", labelHi: "Present Staff", labelEn: "Present Staff", type: "number", required: true, defaultValue: "18" },
          { key: "leaveCount", labelHi: "On Leave", labelEn: "On Leave", type: "number", required: true, defaultValue: "2" },
        ],
        isDefault: true,
      },
    ],
  },
  {
    code: "SAFAI_THANA",
    category: "ROUTINE_ADMINISTRATION",
    nameEn: "Cleanliness (Safai Thana)",
    nameHi: "Cleanliness (Safai)",
    description: "Sanitation check, water/lighting, and cleanliness inspection of police station premises, lockup, and barracks.",
    isEnabled: true,
    usedCount: 15,
    requiresOfficer: true,
    defaultTemplates: [
      {
        id: "tmpl_safai_en",
        typeCode: "SAFAI_THANA",
        title: "Station Inspection & Cleanliness",
        titleHi: "Cleanliness",
        language: "en",
        subjectTemplate: "Safai - Station Inspection & Cleanliness",
        bodyTemplate:
          "At 06:30 AM, comprehensive cleaning and sanitary inspection of police station premises, lockup, mal-khana, barracks, and public reception was conducted. Sanitation, drinking water, and lighting verified in proper order.",
        variables: [],
        isDefault: true,
      },
    ],
  },
  {
    code: "RAVANGI_OFFICER",
    category: "DUTY_MOVEMENT",
    nameEn: "Departure (Ravangi)",
    nameHi: "Departure (Ravangi)",
    description: "Departure of police officer/staff for investigation, raid, patrol, or court appearance.",
    isEnabled: true,
    usedCount: 45,
    requiresOfficer: true,
    requiresVehicle: true,
    requiresCaseReference: true,
    defaultTemplates: [
      {
        id: "tmpl_ravangi_en",
        typeCode: "RAVANGI_OFFICER",
        title: "Departure for Duty / Investigation",
        titleHi: "Departure",
        language: "en",
        subjectTemplate: "Ravangi - Departure for Investigation",
        bodyTemplate:
          "At this time, officer departed from the Police Station along with staff in government vehicle for official duty and field investigation in case enquiry. Arms and logbook verified. Entered in General Diary.",
        variables: [
          { key: "caseRef", labelHi: "Case / Ref", labelEn: "Case / Ref", type: "text", required: false, defaultValue: "CMP-2026-00482" },
          { key: "destination", labelHi: "Destination", labelEn: "Destination", type: "text", required: false, defaultValue: "Sector 7, Kurukshetra" },
        ],
        isDefault: true,
      },
    ],
  },
  {
    code: "WAPSI_OFFICER",
    category: "DUTY_MOVEMENT",
    nameEn: "Arrival (Wapsi)",
    nameHi: "Arrival (Wapsi)",
    description: "Return of police personnel to Police Station after conducting enquiry, patrol, or duty.",
    isEnabled: true,
    usedCount: 38,
    requiresOfficer: true,
    defaultTemplates: [
      {
        id: "tmpl_wapsi_en",
        typeCode: "WAPSI_OFFICER",
        title: "Arrival from Duty / Investigation",
        titleHi: "Arrival",
        language: "en",
        subjectTemplate: "Wapsi - Return from Duty",
        bodyTemplate:
          "At this time, officer returned safely to the Police Station along with staff after concluding official field enquiry, spot inspection, and case investigation. Arms deposited in order. Entered in General Diary.",
        variables: [
          { key: "destination", labelHi: "Returned From", labelEn: "Returned From", type: "text", required: false, defaultValue: "Sector 7" },
        ],
        isDefault: true,
      },
    ],
  },
  {
    code: "DUTY_ASSIGNMENT",
    category: "DUTY_MOVEMENT",
    nameEn: "Duty Assignment (Sentry Relief)",
    nameHi: "Duty Assignment",
    description: "Relief of sentry guard, lockup guard, and shift turnover with arms handover.",
    isEnabled: true,
    usedCount: 29,
    requiresOfficer: true,
    defaultTemplates: [
      {
        id: "tmpl_duty_en",
        typeCode: "DUTY_ASSIGNMENT",
        title: "Sentry Relief & Duty Turnover",
        titleHi: "Duty Turnover",
        language: "en",
        subjectTemplate: "Duty Change - Sentry Relief & Shift Turnover",
        bodyTemplate:
          "At this time, sentry guard and shift turnover took place. Government arms, ammunition, and lockup charge handed over in proper condition. New sentry alert on duty.",
        variables: [],
        isDefault: true,
      },
    ],
  },
  {
    code: "COMPLAINT_RECEIVED",
    category: "INVESTIGATION_PROCESS",
    nameEn: "Complaint Intake",
    nameHi: "Complaint Intake",
    description: "Intake of citizen application/complaint at station front desk.",
    isEnabled: true,
    usedCount: 52,
    requiresOfficer: true,
    requiresCaseReference: true,
    defaultTemplates: [
      {
        id: "tmpl_complaint_en",
        typeCode: "COMPLAINT_RECEIVED",
        title: "Citizen Complaint Intake",
        titleHi: "Complaint Intake",
        language: "en",
        subjectTemplate: "Complaint Received - Citizen Application Intake",
        bodyTemplate:
          "At this time, citizen submitted a written complaint. Intake acknowledged, computerized docket generated in CMS, and placed before SHO for enquiry officer assignment.",
        variables: [
          { key: "complaintNo", labelHi: "Complaint No", labelEn: "Complaint No", type: "text", required: true, defaultValue: "CMP-2026-00486" },
        ],
        isDefault: true,
      },
    ],
  },
  {
    code: "FIR_REGISTRATION",
    category: "INVESTIGATION_PROCESS",
    nameEn: "FIR Registration",
    nameHi: "FIR Registration",
    description: "Recording registration of formal First Information Report under BNSS 173.",
    isEnabled: true,
    usedCount: 20,
    requiresOfficer: true,
    requiresCaseReference: true,
    defaultTemplates: [
      {
        id: "tmpl_fir_en",
        typeCode: "FIR_REGISTRATION",
        title: "FIR Lodged Intimation",
        titleHi: "FIR Lodged",
        language: "en",
        subjectTemplate: "FIR Registered - Criminal Case Lodged",
        bodyTemplate:
          "At this time, formal FIR was registered under relevant legal sections upon substantiation of cognizable offence. Investigation assigned to investigating officer.",
        variables: [
          { key: "firNo", labelHi: "FIR No", labelEn: "FIR No", type: "text", required: true, defaultValue: "142/2026" },
        ],
        isDefault: true,
      },
    ],
  },
  {
    code: "ARREST_ACCUSED",
    category: "INVESTIGATION_PROCESS",
    nameEn: "Arrest of Accused",
    nameHi: "Arrest of Accused",
    description: "Custodial intake of arrested accused person with medical inspection and intimation to relatives.",
    isEnabled: true,
    usedCount: 18,
    requiresOfficer: true,
    requiresCaseReference: true,
    defaultTemplates: [
      {
        id: "tmpl_arrest_en",
        typeCode: "ARREST_ACCUSED",
        title: "Arrest of Accused Person",
        titleHi: "Arrest",
        language: "en",
        subjectTemplate: "Arrest of Accused - Custodial Intake",
        bodyTemplate:
          "At this time, accused person was produced under arrest following legal procedure. Medical examination conducted and intimation given to family members.",
        variables: [
          { key: "accusedName", labelHi: "Accused Name", labelEn: "Accused Name", type: "text", required: true, defaultValue: "Joginder Singh" },
        ],
        isDefault: true,
      },
    ],
  },
  {
    code: "RELEASE_ACCUSED",
    category: "INVESTIGATION_PROCESS",
    nameEn: "Release / Bail of Accused",
    nameHi: "Release / Bail",
    description: "Discharge of accused from police lockup upon bail bond or court order.",
    isEnabled: true,
    usedCount: 11,
    requiresOfficer: true,
    requiresCaseReference: true,
    defaultTemplates: [
      {
        id: "tmpl_release_en",
        typeCode: "RELEASE_ACCUSED",
        title: "Release / Bail of Accused",
        titleHi: "Release / Bail",
        language: "en",
        subjectTemplate: "Release of Accused - Court Bail Granted",
        bodyTemplate:
          "At this time, accused person was released from police custody following valid bail order from the competent court.",
        variables: [],
        isDefault: true,
      },
    ],
  },
  {
    code: "PROPERTY_DEPOSIT",
    category: "PROPERTY_MALKHANA",
    nameEn: "Malkhana Property Deposit",
    nameHi: "Property Deposit",
    description: "Deposit of seized case property/weapons into station Malkhana Register No. XIX.",
    isEnabled: true,
    usedCount: 16,
    requiresOfficer: true,
    requiresCaseReference: true,
    defaultTemplates: [
      {
        id: "tmpl_prop_en",
        typeCode: "PROPERTY_DEPOSIT",
        title: "Case Property Malkhana Deposit",
        titleHi: "Property Deposit",
        language: "en",
        subjectTemplate: "Malkhana - Case Property Deposited",
        bodyTemplate:
          "At this time, case property/seized items were formally deposited into the Malkhana under Register No. XIX.",
        variables: [],
        isDefault: true,
      },
    ],
  },
  {
    code: "COURT_PRODUCTION",
    category: "COURT_DOCUMENTATION",
    nameEn: "Court Production",
    nameHi: "Court Production",
    description: "Escorting arrested accused for production before Judicial Magistrate.",
    isEnabled: true,
    usedCount: 19,
    requiresOfficer: true,
    requiresCaseReference: true,
    defaultTemplates: [
      {
        id: "tmpl_court_en",
        typeCode: "COURT_PRODUCTION",
        title: "Court Production Entry",
        titleHi: "Court Production",
        language: "en",
        subjectTemplate: "Court Production - Accused Produced Before Magistrate",
        bodyTemplate:
          "At this time, accused was escorted under secure guard to the competent court for remand/judicial hearing.",
        variables: [],
        isDefault: true,
      },
    ],
  },
  {
    code: "VEHICLE_MOVEMENT",
    category: "DUTY_MOVEMENT",
    nameEn: "Vehicle Movement",
    nameHi: "Vehicle Movement",
    description: "Official vehicle departure, arrival, driver allocation, and kilometer log recording.",
    isEnabled: true,
    usedCount: 24,
    requiresOfficer: true,
    requiresVehicle: true,
    defaultTemplates: [
      {
        id: "tmpl_veh_en",
        typeCode: "VEHICLE_MOVEMENT",
        title: "Government Vehicle Movement",
        titleHi: "Vehicle Movement",
        language: "en",
        subjectTemplate: "Government Vehicle - Movement Recorded",
        bodyTemplate:
          "At this time, government patrol vehicle departed / returned for official police duties. Logbook kilometer reading and fuel verified.",
        variables: [],
        isDefault: true,
      },
    ],
  },
  {
    code: "BEAT_PATROLLING",
    category: "DUTY_MOVEMENT",
    nameEn: "Beat Patrolling",
    nameHi: "Beat Patrolling",
    description: "Dispatch of foot and mobile patrolling teams for crime prevention and market security.",
    isEnabled: true,
    usedCount: 31,
    requiresOfficer: true,
    defaultTemplates: [
      {
        id: "tmpl_beat_en",
        typeCode: "BEAT_PATROLLING",
        title: "Beat Patrolling & Area Vigilance",
        titleHi: "Beat Patrolling",
        language: "en",
        subjectTemplate: "Beat Duty - Area Patrolling & Chequing",
        bodyTemplate:
          "At this time, beat patrolling staff dispatched for intensive night patrolling, vehicle chequing, and crime prevention in market and residential areas.",
        variables: [],
        isDefault: true,
      },
    ],
  },
  {
    code: "SUPERVISORY_CHECKING",
    category: "ROUTINE_ADMINISTRATION",
    nameEn: "Supervisory Inspection",
    nameHi: "Supervisory Inspection",
    description: "Surprise visit and inspection by DSP, SP, or supervisory officer.",
    isEnabled: true,
    usedCount: 10,
    requiresOfficer: true,
    defaultTemplates: [
      {
        id: "tmpl_sup_en",
        typeCode: "SUPERVISORY_CHECKING",
        title: "Supervisory Inspection",
        titleHi: "Supervisory Visit",
        language: "en",
        subjectTemplate: "Supervisory Inspection - Senior Officer Visit",
        bodyTemplate:
          "At this time, senior supervisory officer arrived for surprise checking of the Police Station, records, lockup, and staff alertness.",
        variables: [],
        isDefault: true,
      },
    ],
  },
  {
    code: "INFORMATION_RECEIVED",
    category: "INVESTIGATION_PROCESS",
    nameEn: "General Information",
    nameHi: "General Information",
    description: "Receipt of public information, intelligence, or administrative notification.",
    isEnabled: true,
    usedCount: 15,
    requiresOfficer: false,
    defaultTemplates: [
      {
        id: "tmpl_info_en",
        typeCode: "INFORMATION_RECEIVED",
        title: "General Information Entry",
        titleHi: "General Information",
        language: "en",
        subjectTemplate: "Information Received - General Station Entry",
        bodyTemplate:
          "At this time, information received regarding local law and order development. Relevant entries noted for station record.",
        variables: [],
        isDefault: true,
      },
    ],
  },
];
