import { GDEntryCategory, GDEntryTypeConfig, GDTemplate } from "@/types/generalDiary";

// ------------------------------------------------------------------
// OFFICIAL HARYANA CCTNS GENERAL DIARY (Roznamcha) — GD Type master list
// Names and order exactly as per the official Haryana CCTNS module.
// ------------------------------------------------------------------

export const CCTNS_OFFICIAL_GD_TYPE_NAMES: string[] = [
  "Absent",
  "Accidental death",
  "Accidents/Incidents",
  "Accused in Police Custody",
  "Accused Sent to Judicial Custody",
  "Accused Sent to Transit Remand",
  "Arrest in Preventive Action",
  "Arrest/Re-Arrest/Surrender",
  "Arrested accused re-admitted in lock up after investigation",
  "Arrested accused taken out of lock up for investigation",
  "Arrival",
  "Arrival/Return",
  "Assigning Officer Incharge",
  "Attending court for evidence",
  "Bail",
  "Bandi Muljim into PS Lock Up",
  "Bandobast",
  "Bomb blast",
  "Burn cases",
  "Case Diary",
  "Cash book entry",
  "Change of DO",
  "Change of Guard",
  "Change of HCM",
  "Change of Malkhana Muhararar",
  "Change of Report Writer",
  "Change of Santri",
  "Checking of History-Sheeters & Known Criminals",
  "Citizen Information/Tip Received",
  "Close of GD",
  "Combing operations",
  "Confidential Reports",
  "Control Room Information/PCR Call",
  "Criminal case",
  "Current/future political, social, religious etc. activities",
  "Dead Animal",
  "Defaults of police personnel",
  "Departure",
  "Detention of Juvenile offender",
  "ERSS ERV",
  "Execution of summon/warrant",
  "FIR Transfer",
  "Fire Incident",
  "Firing",
  "Flag Hoisting",
  "Good morning squad",
  "Handing over of Property/Charge",
  "Help provided to police staff of other police stations for investigation",
  "Information from control room",
  "Information from hospital",
  "Information of functions/occasions",
  "Inspection note",
  "Interrogation/search/checking report",
  "Investigation Reports",
  "Juvenile Case",
  "Leave/Seek report",
  "Lockup Inspection",
  "Lost Property",
  "Malkhana Inspection",
  "Medical check-up of arrested accused",
  "Medical Rest",
  "Medico Legal Case",
  "Missing Cattle",
  "Missing person",
  "Muddemal sent for expert’s opinion",
  "Nakabandi",
  "Night round",
  "Nikasi Muljim from PS Lock Up",
  "Nil report for last 2 hours",
  "Non-Cognizable Report",
  "Opening of GD",
  "Others",
  "Patrolling",
  "PCR Call",
  "Preventive Action",
  "Property Deposited in Malkhana",
  "Property Release from Malkhana",
  "Property Seizure",
  "Public relation activities",
  "Record of Arrested Accused in lockup",
  "Remand",
  "Roll Call",
  "RukkaGD",
  "Search report",
  "Sensitive guard checking",
  "Special entry",
  "Station Diary charge",
  "Station Diary summary",
  "Summary of Malkhana",
  "Summary of Pending Cases",
  "Traveller/passenger checking",
  "UIDB/Identified Dead Body",
  "Unclaimed/Abandoned Property",
  "Unidentified Found Person",
  "Village visitation",
  "Visit of senior police officers",
  "Visitors of arrested accused",
  "Work Distribution",
];

// CCTNS category bucket for each official entry (defaults to ROUTINE_ADMINISTRATION)
const CATEGORY_OVERRIDES: Record<string, GDEntryCategory> = {
  // Duty movement
  Arrival: "DUTY_MOVEMENT",
  "Arrival/Return": "DUTY_MOVEMENT",
  Departure: "DUTY_MOVEMENT",
  "ERSS ERV": "DUTY_MOVEMENT",
  "Night round": "DUTY_MOVEMENT",
  Patrolling: "DUTY_MOVEMENT",
  "Village visitation": "DUTY_MOVEMENT",
  // Law & order
  Bandobast: "LAW_AND_ORDER",
  "Bomb blast": "LAW_AND_ORDER",
  "Burn cases": "LAW_AND_ORDER",
  "Combing operations": "LAW_AND_ORDER",
  "Current/future political, social, religious etc. activities": "LAW_AND_ORDER",
  "Fire Incident": "LAW_AND_ORDER",
  Firing: "LAW_AND_ORDER",
  Nakabandi: "LAW_AND_ORDER",
  "Preventive Action": "LAW_AND_ORDER",
  "Arrest in Preventive Action": "LAW_AND_ORDER",
  "Traveller/passenger checking": "LAW_AND_ORDER",
  "Good morning squad": "LAW_AND_ORDER",
  // Investigation process
  "Accused in Police Custody": "INVESTIGATION_PROCESS",
  "Accused Sent to Judicial Custody": "INVESTIGATION_PROCESS",
  "Accused Sent to Transit Remand": "INVESTIGATION_PROCESS",
  "Arrest/Re-Arrest/Surrender": "INVESTIGATION_PROCESS",
  "Arrested accused re-admitted in lock up after investigation": "INVESTIGATION_PROCESS",
  "Arrested accused taken out of lock up for investigation": "INVESTIGATION_PROCESS",
  "Case Diary": "INVESTIGATION_PROCESS",
  "Criminal case": "INVESTIGATION_PROCESS",
  "Detention of Juvenile offender": "INVESTIGATION_PROCESS",
  "Interrogation/search/checking report": "INVESTIGATION_PROCESS",
  "Investigation Reports": "INVESTIGATION_PROCESS",
  "Juvenile Case": "INVESTIGATION_PROCESS",
  "Medical check-up of arrested accused": "INVESTIGATION_PROCESS",
  "Record of Arrested Accused in lockup": "INVESTIGATION_PROCESS",
  Remand: "INVESTIGATION_PROCESS",
  RukkaGD: "INVESTIGATION_PROCESS",
  "Search report": "INVESTIGATION_PROCESS",
  "Nikasi Muljim from PS Lock Up": "INVESTIGATION_PROCESS",
  "Bandi Muljim into PS Lock Up": "INVESTIGATION_PROCESS",
  "Visitors of arrested accused": "INVESTIGATION_PROCESS",
  "Help provided to police staff of other police stations for investigation":
    "INVESTIGATION_PROCESS",
  "Lockup Inspection": "INVESTIGATION_PROCESS",
  // Court & documentation
  "Attending court for evidence": "COURT_DOCUMENTATION",
  Bail: "COURT_DOCUMENTATION",
  "Execution of summon/warrant": "COURT_DOCUMENTATION",
  "FIR Transfer": "COURT_DOCUMENTATION",
  "Non-Cognizable Report": "COURT_DOCUMENTATION",
  "Summary of Pending Cases": "COURT_DOCUMENTATION",
  // Property / Malkhana
  "Handing over of Property/Charge": "PROPERTY_MALKHANA",
  "Lost Property": "PROPERTY_MALKHANA",
  "Malkhana Inspection": "PROPERTY_MALKHANA",
  "Muddemal sent for expert’s opinion": "PROPERTY_MALKHANA",
  "Property Deposited in Malkhana": "PROPERTY_MALKHANA",
  "Property Release from Malkhana": "PROPERTY_MALKHANA",
  "Property Seizure": "PROPERTY_MALKHANA",
  "Summary of Malkhana": "PROPERTY_MALKHANA",
  "Unclaimed/Abandoned Property": "PROPERTY_MALKHANA",
  // Miscellaneous
  "Accidental death": "MISCELLANEOUS",
  "Accidents/Incidents": "MISCELLANEOUS",
  "Dead Animal": "MISCELLANEOUS",
  "Missing Cattle": "MISCELLANEOUS",
  "Missing person": "MISCELLANEOUS",
  "Medico Legal Case": "MISCELLANEOUS",
  "UIDB/Identified Dead Body": "MISCELLANEOUS",
  "Unidentified Found Person": "MISCELLANEOUS",
  "Citizen Information/Tip Received": "MISCELLANEOUS",
  "Control Room Information/PCR Call": "MISCELLANEOUS",
  "Information from control room": "MISCELLANEOUS",
  "Information from hospital": "MISCELLANEOUS",
  "Information of functions/occasions": "MISCELLANEOUS",
  "PCR Call": "MISCELLANEOUS",
  "Sensitive guard checking": "MISCELLANEOUS",
};

// Entry types that specifically involve a particular officer
const OFFICER_REQUIRED: Set<string> = new Set([
  "Arrival",
  "Arrival/Return",
  "Departure",
  "Assigning Officer Incharge",
  "Change of DO",
  "Change of Guard",
  "Change of HCM",
  "Change of Malkhana Muhararar",
  "Change of Report Writer",
  "Change of Santri",
  "Arrest/Re-Arrest/Surrender",
  "Arrest in Preventive Action",
  "Accused Sent to Judicial Custody",
  "Accused Sent to Transit Remand",
  "Bandi Muljim into PS Lock Up",
  "Nikasi Muljim from PS Lock Up",
  "Medical check-up of arrested accused",
  "Record of Arrested Accused in lockup",
  "Medical Rest",
  "Leave/Seek report",
  "Remand",
  "Bail",
  "Execution of summon/warrant",
  "Attending court for evidence",
  "RukkaGD",
  "Roll Call",
  "Station Diary charge",
  "Work Distribution",
  "Visit of senior police officers",
  "Interrogation/search/checking report",
  "Defaults of police personnel",
]);

function toOfficialCode(name: string): string {
  return name
    .toUpperCase()
    .replace(/[^A-Z0-9]+/g, "_")
    .replace(/^_+|_+$/g, "");
}

export const CCTNS_OFFICIAL_GD_TYPES: GDEntryTypeConfig[] =
  CCTNS_OFFICIAL_GD_TYPE_NAMES.map((name) => ({
    code: toOfficialCode(name),
    category: CATEGORY_OVERRIDES[name] ?? "ROUTINE_ADMINISTRATION",
    nameEn: name,
    nameHi: name,
    description: `Official Haryana CCTNS General Diary entry type: ${name}`,
    isEnabled: true,
    usedCount: 0,
    requiresOfficer: OFFICER_REQUIRED.has(name),
    defaultTemplates: [] as GDTemplate[],
  }));

// Seed master list = official CCTNS list (replaces the old ad-hoc list)
export const INITIAL_GD_TYPES: GDEntryTypeConfig[] = CCTNS_OFFICIAL_GD_TYPES;

// Pre-CCTNS legacy type codes — must never surface as custom dropdown items
export const LEGACY_GD_TYPE_CODES: Set<string> = new Set([
  "AAGAZ_ROZNAMCHA",
  "SAFAI_THANA",
  "STAFF_GINTI",
  "GINTI_STAFF",
  "RAVANGI_OFFICER",
  "WAPSI_OFFICER",
  "BANDI_ROZNAMCHA",
  "COMPLAINT_INTAKE",
  "COMPLAINT_RECEIVED",
  "FIR_REGISTRATION",
  "BEAT_PATROLLING",
  "PROPERTY_DEPOSIT",
  "COURT_PRODUCTION",
  "VEHICLE_MOVEMENT",
  "OTHER_MISCELLANEOUS",
  "INFORMATION_RECEIVED",
  "SUPERVISORY_CHECKING",
  "ARREST_ACCUSED",
  "RELEASE_ACCUSED",
  "DUTY_ASSIGNMENT",
]);

// Commonly used official codes referenced across the app
export const GD_TYPE = {
  OPENING: "OPENING_OF_GD",
  CLOSE: "CLOSE_OF_GD",
  DEPARTURE: "DEPARTURE",
  ARRIVAL: "ARRIVAL_RETURN",
  ROLL_CALL: "ROLL_CALL",
  NAKABANDI: "NAKABANDI",
  MISSING_PERSON: "MISSING_PERSON",
  CRIMINAL_CASE: "CRIMINAL_CASE",
  CITIZEN_INFORMATION: "CITIZEN_INFORMATION_TIP_RECEIVED",
  PROPERTY_SEIZURE: "PROPERTY_SEIZURE",
  OTHERS: "OTHERS",
} as const;
