// src/lib/jurisdictionData.ts
// Comprehensive Indian States, Districts, and Police Stations Directory
// Specifically optimized for Haryana Police and neighboring jurisdictions

export interface DistrictData {
  district: string;
  policeStations: string[];
}

export interface StateJurisdiction {
  state: string;
  districts: DistrictData[];
}

export const JURISDICTION_DATA: StateJurisdiction[] = [
  {
    state: "Haryana",
    districts: [
      {
        district: "Gurugram",
        policeStations: [
          "Sector 29 Police Station",
          "DLF Phase 1 Police Station",
          "DLF Phase 2 Police Station",
          "DLF Phase 3 Police Station",
          "Sushant Lok Police Station",
          "Sector 40 Police Station",
          "Sector 53 Police Station",
          "Sector 56 Police Station",
          "Cyber Crime Gurugram",
          "Women Police Station West",
          "Women Police Station East",
          "Sadar Gurugram Police Station",
          "City Gurugram Police Station",
          "Sector 14 Police Station",
          "Sector 18 Police Station",
          "Sector 10A Police Station",
          "Sector 37 Police Station",
          "Kherki Daula Police Station",
          "Badshahpur Police Station",
          "Sohna Police Station",
          "Pataudi Police Station",
          "Manesar Police Station",
          "Bilaspur Police Station",
          "Rajendra Park Police Station",
          "Bajghera Police Station",
          "New Colony Police Station",
          "Shivaji Nagar Police Station",
        ],
      },
      {
        district: "Kurukshetra",
        policeStations: [
          "PS City Thanesar",
          "PS Sadar Thanesar",
          "PS Krishna Gate",
          "PS Shahabad",
          "PS Pehowa",
          "PS Ladwa",
          "PS Babain",
          "PS Ismailabad",
          "PS Jhansa",
          "PS Cyber Crime Kurukshetra",
          "PS Women Kurukshetra",
          "PS Traffic Kurukshetra",
        ],
      },
      {
        district: "Faridabad",
        policeStations: [
          "PS Central Faridabad",
          "PS Old Faridabad",
          "PS NIT Faridabad",
          "PS Sector 7",
          "PS Sector 8",
          "PS Sector 31",
          "PS Sarai Khawaja",
          "PS Surajkund",
          "PS Ballabgarh City",
          "PS Ballabgarh Sadar",
          "PS Mujesar",
          "PS Tigaon",
          "PS Chhainsa",
          "PS Dhauj",
          "PS Sector 58",
          "PS Bhupani",
          "PS Kotwali Faridabad",
          "PS Women NIT",
          "PS Cyber Crime Faridabad",
        ],
      },
      {
        district: "Ambala",
        policeStations: [
          "PS Ambala City",
          "PS Ambala Cantt",
          "PS Baldev Nagar",
          "PS Sadar Ambala",
          "PS Parao",
          "PS Mahesh Nagar",
          "PS Mullana",
          "PS Barara",
          "PS Naraingarh",
          "PS Shahzadpur",
          "PS Panjokhra",
          "PS Women Ambala",
          "PS Cyber Crime Ambala",
        ],
      },
      {
        district: "Panchkula",
        policeStations: [
          "PS Sector 5 Panchkula",
          "PS Sector 14 Panchkula",
          "PS Sector 20 Panchkula",
          "PS Mansa Devi Complex",
          "PS Chandimandir",
          "PS Pinjore",
          "PS Kalka",
          "PS Raipur Rani",
          "PS Women Panchkula",
          "PS Cyber Crime Panchkula",
        ],
      },
      {
        district: "Karnal",
        policeStations: [
          "PS City Karnal",
          "PS Sadar Karnal",
          "PS Civil Lines Karnal",
          "PS Ram Nagar Karnal",
          "PS Taraori",
          "PS Gharaunda",
          "PS Indri",
          "PS Assandh",
          "PS Nissing",
          "PS Kunjpura",
          "PS Madhuban",
          "PS Butana",
          "PS Women Karnal",
          "PS Cyber Crime Karnal",
        ],
      },
      {
        district: "Panipat",
        policeStations: [
          "PS City Panipat",
          "PS Sadar Panipat",
          "PS Model Town Panipat",
          "PS Chandni Bagh",
          "PS Quilla Panipat",
          "PS Industrial Area Panipat",
          "PS Samalkha",
          "PS Israna",
          "PS Matlauda",
          "PS Bapoli",
          "PS Sanoli",
          "PS Women Panipat",
          "PS Cyber Crime Panipat",
        ],
      },
      {
        district: "Sonipat",
        policeStations: [
          "PS City Sonipat",
          "PS Sadar Sonipat",
          "PS Civil Lines Sonipat",
          "PS Sector 27 Sonipat",
          "PS Rai",
          "PS Kundli",
          "PS Murthal",
          "PS Ganaur",
          "PS Kharkhoda",
          "PS Gohana City",
          "PS Gohana Sadar",
          "PS Baroda",
          "PS Mohana",
          "PS Women Sonipat",
          "PS Cyber Crime Sonipat",
        ],
      },
      {
        district: "Rohtak",
        policeStations: [
          "PS City Rohtak",
          "PS Sadar Rohtak",
          "PS Civil Lines Rohtak",
          "PS Urban Estate Rohtak",
          "PS Shivaji Colony",
          "PS PGIMS Rohtak",
          "PS Arya Nagar Rohtak",
          "PS Kalanaur",
          "PS Meham",
          "PS Sampla",
          "PS Lahli",
          "PS IMT Rohtak",
          "PS Women Rohtak",
          "PS Cyber Crime Rohtak",
        ],
      },
      {
        district: "Hisar",
        policeStations: [
          "PS City Hisar",
          "PS Sadar Hisar",
          "PS Civil Lines Hisar",
          "PS Urban Estate Hisar",
          "PS HTM Hisar",
          "PS Mill Gate Hisar",
          "PS Hansi City",
          "PS Hansi Sadar",
          "PS Barwala",
          "PS Narnaund",
          "PS Uklana",
          "PS Bass",
          "PS Agroha",
          "PS Women Hisar",
          "PS Cyber Crime Hisar",
        ],
      },
      {
        district: "Sirsa",
        policeStations: [
          "PS City Sirsa",
          "PS Sadar Sirsa",
          "PS Civil Lines Sirsa",
          "PS Rania",
          "PS Ellenabad",
          "PS Dabwali City",
          "PS Dabwali Sadar",
          "PS Kalanwali",
          "PS Ding",
          "PS Baragudha",
          "PS Rori",
          "PS Chopta",
          "PS Women Sirsa",
          "PS Cyber Crime Sirsa",
        ],
      },
      {
        district: "Jhajjar",
        policeStations: [
          "PS City Jhajjar",
          "PS Sadar Jhajjar",
          "PS Bahadurgarh City",
          "PS Bahadurgarh Sadar",
          "PS Line Par Bahadurgarh",
          "PS Sector 6 Bahadurgarh",
          "PS Beri",
          "PS Salhawas",
          "PS Machhroli",
          "PS Dujana",
          "PS Aasoda",
          "PS Women Jhajjar",
          "PS Cyber Crime Jhajjar",
        ],
      },
      {
        district: "Rewari",
        policeStations: [
          "PS City Rewari",
          "PS Sadar Rewari",
          "PS Model Town Rewari",
          "PS Rampura",
          "PS Dharuhera",
          "PS Bawal",
          "PS Khol",
          "PS Kasola",
          "PS Jatusana",
          "PS Rohrai",
          "PS Sector 6 Rewari",
          "PS Women Rewari",
          "PS Cyber Crime Rewari",
        ],
      },
      {
        district: "Palwal",
        policeStations: [
          "PS City Palwal",
          "PS Sadar Palwal",
          "PS Camp Palwal",
          "PS Hodal",
          "PS Hassanpur",
          "PS Hathin",
          "PS Bahin",
          "PS Mundkati",
          "PS Chandhat",
          "PS Gadhpuri",
          "PS Women Palwal",
          "PS Cyber Crime Palwal",
        ],
      },
      {
        district: "Bhiwani",
        policeStations: [
          "PS City Bhiwani",
          "PS Sadar Bhiwani",
          "PS Civil Lines Bhiwani",
          "PS Industrial Area Bhiwani",
          "PS Tosham",
          "PS Siwani",
          "PS Loharu",
          "PS Bawani Khera",
          "PS Bahl",
          "PS Women Bhiwani",
          "PS Cyber Crime Bhiwani",
        ],
      },
      {
        district: "Yamunanagar",
        policeStations: [
          "PS City Yamunanagar",
          "PS Sadar Yamunanagar",
          "PS City Jagadhri",
          "PS Sadar Jagadhri",
          "PS Farakpur",
          "PS Gandhi Nagar Yamunanagar",
          "PS Chhachhrauli",
          "PS Bilaspur",
          "PS Radaur",
          "PS Pratap Nagar",
          "PS Buria",
          "PS Jadhoda",
          "PS Women Yamunanagar",
          "PS Cyber Crime Yamunanagar",
        ],
      },
      {
        district: "Fatehabad",
        policeStations: [
          "PS City Fatehabad",
          "PS Sadar Fatehabad",
          "PS Tohana City",
          "PS Tohana Sadar",
          "PS Ratia",
          "PS Bhuna",
          "PS Jakhal",
          "PS Bhattu Kalan",
          "PS Bighar",
          "PS Women Fatehabad",
          "PS Cyber Crime Fatehabad",
        ],
      },
      {
        district: "Kaithal",
        policeStations: [
          "PS City Kaithal",
          "PS Sadar Kaithal",
          "PS Civil Lines Kaithal",
          "PS Titram",
          "PS Cheeka",
          "PS Guhla",
          "PS Kalayat",
          "PS Pundri",
          "PS Dhand",
          "PS Rajound",
          "PS Siwan",
          "PS Women Kaithal",
          "PS Cyber Crime Kaithal",
        ],
      },
      {
        district: "Jind",
        policeStations: [
          "PS City Jind",
          "PS Sadar Jind",
          "PS Civil Lines Jind",
          "PS Safidon",
          "PS Narwana City",
          "PS Narwana Sadar",
          "PS Julana",
          "PS Uchana",
          "PS Garhi",
          "PS Alewa",
          "PS Pillukhera",
          "PS Women Jind",
          "PS Cyber Crime Jind",
        ],
      },
      {
        district: "Mahendragarh",
        policeStations: [
          "PS City Narnaul",
          "PS Sadar Narnaul",
          "PS Mahendragarh City",
          "PS Mahendragarh Sadar",
          "PS Kanina",
          "PS Ateli",
          "PS Nangal Choudhary",
          "PS Satnali",
          "PS Nizampur",
          "PS Women Narnaul",
          "PS Cyber Crime Narnaul",
        ],
      },
      {
        district: "Charkhi Dadri",
        policeStations: [
          "PS City Charkhi Dadri",
          "PS Sadar Charkhi Dadri",
          "PS Badhra",
          "PS Bond Kalan",
          "PS Jhojhu Kalan",
          "PS Baund Kalan",
          "PS Women Charkhi Dadri",
          "PS Cyber Crime Charkhi Dadri",
        ],
      },
      {
        district: "Nuh",
        policeStations: [
          "PS Nuh",
          "PS Taoru",
          "PS Punhana",
          "PS Ferozepur Jhirka",
          "PS Nagina",
          "PS Pinangwan",
          "PS Bichhor",
          "PS Rojka Meo",
          "PS Sadar Nuh",
          "PS Women Nuh",
          "PS Cyber Crime Nuh",
        ],
      },
    ],
  },
  {
    state: "Delhi",
    districts: [
      {
        district: "New Delhi",
        policeStations: [
          "PS Connaught Place",
          "PS Parliament Street",
          "PS Mandir Marg",
          "PS Chanakyapuri",
          "PS Tughlak Road",
          "PS Tilak Marg",
          "PS Barakhamba Road",
        ],
      },
      {
        district: "South Delhi",
        policeStations: [
          "PS Hauz Khas",
          "PS Malviya Nagar",
          "PS Saket",
          "PS Mehrauli",
          "PS Neb Sarai",
          "PS Fatehpur Beri",
          "PS Safdarjung Enclave",
        ],
      },
      {
        district: "South East Delhi",
        policeStations: [
          "PS Kalkaji",
          "PS Lajpat Nagar",
          "PS Amar Colony",
          "PS Okhla",
          "PS Sarita Vihar",
          "PS Badarpur",
          "PS Govindpuri",
          "PS Jamia Nagar",
        ],
      },
      {
        district: "South West Delhi",
        policeStations: [
          "PS Vasant Vihar",
          "PS Vasant Kunj North",
          "PS Vasant Kunj South",
          "PS Delhi Cantt",
          "PS Kapashera",
          "PS Sarojini Nagar",
        ],
      },
      {
        district: "Dwarka",
        policeStations: [
          "PS Dwarka South",
          "PS Dwarka North",
          "PS Dwarka Sector 23",
          "PS Palam Village",
          "PS Najafgarh",
          "PS Baba Haridas Nagar",
          "PS Chhawla",
          "PS Jaffarpur Kalan",
        ],
      },
      {
        district: "West Delhi",
        policeStations: [
          "PS Rajouri Garden",
          "PS Tilak Nagar",
          "PS Janakpuri",
          "PS Vikas Puri",
          "PS Punjabi Bagh",
          "PS Moti Nagar",
          "PS Kirti Nagar",
          "PS Hari Nagar",
        ],
      },
      {
        district: "North West Delhi",
        policeStations: [
          "PS Model Town",
          "PS Bharat Nagar",
          "PS Ashok Vihar",
          "PS Subhash Place",
          "PS Keshav Puram",
          "PS Shalimar Bagh",
          "PS Maurya Enclave",
        ],
      },
      {
        district: "North Delhi",
        policeStations: [
          "PS Kotwali Delhi",
          "PS Lahori Gate",
          "PS Kashmere Gate",
          "PS Civil Lines Delhi",
          "PS Timarpur",
          "PS Roop Nagar",
          "PS Maurice Nagar",
          "PS Sadar Bazar Delhi",
        ],
      },
      {
        district: "Central Delhi",
        policeStations: [
          "PS Daryaganj",
          "PS Paharganj",
          "PS Kamla Market",
          "PS Chandni Mahal",
          "PS Karol Bagh",
          "PS Rajinder Nagar",
          "PS DBG Road",
          "PS IP Estate",
        ],
      },
      {
        district: "East Delhi",
        policeStations: [
          "PS Preet Vihar",
          "PS Shakarpur",
          "PS Laxmi Nagar",
          "PS Madhu Vihar",
          "PS Mayur Vihar",
          "PS Kalyanpuri",
          "PS Pandav Nagar",
          "PS Ghazipur",
        ],
      },
      {
        district: "Shahdara",
        policeStations: [
          "PS Anand Vihar",
          "PS Vivek Vihar",
          "PS Seemapuri",
          "PS GTB Enclave",
          "PS Farsh Bazar",
          "PS Shahdara",
          "PS Mansarovar Park",
        ],
      },
      {
        district: "North East Delhi",
        policeStations: [
          "PS Seelampur",
          "PS Jafrabad",
          "PS Bhajanpura",
          "PS Khajuri Khas",
          "PS Karawal Nagar",
          "PS Dayalpur",
          "PS Gokulpuri",
          "PS Shastri Park",
        ],
      },
    ],
  },
  {
    state: "Punjab",
    districts: [
      {
        district: "Mohali (SAS Nagar)",
        policeStations: [
          "PS Phase 1 Mohali",
          "PS Phase 8 Mohali",
          "PS Phase 11 Mohali",
          "PS Matour",
          "PS Sohana",
          "PS Zirakpur",
          "PS Kharar",
          "PS Dera Bassi",
          "PS Lalru",
        ],
      },
      {
        district: "Patiala",
        policeStations: [
          "PS Kotwali Patiala",
          "PS Civil Lines Patiala",
          "PS Lahori Gate Patiala",
          "PS Sadar Patiala",
          "PS Urban Estate Patiala",
          "PS Tripuri",
          "PS Samana",
          "PS Nabha",
          "PS Rajpura City",
          "PS Rajpura Sadar",
        ],
      },
      {
        district: "Ludhiana",
        policeStations: [
          "PS Division 1 Ludhiana",
          "PS Division 2 Ludhiana",
          "PS Division 5 Ludhiana",
          "PS Civil Lines Ludhiana",
          "PS Sarabha Nagar",
          "PS Model Town Ludhiana",
          "PS PAU Ludhiana",
          "PS Focal Point",
        ],
      },
      {
        district: "Amritsar",
        policeStations: [
          "PS Kotwali Amritsar",
          "PS Civil Lines Amritsar",
          "PS Cantonment Amritsar",
          "PS B-Division Amritsar",
          "PS D-Division Amritsar",
          "PS Sadar Amritsar",
          "PS Chheharta",
        ],
      },
      {
        district: "Jalandhar",
        policeStations: [
          "PS Division 1 Jalandhar",
          "PS Division 2 Jalandhar",
          "PS Division 4 Jalandhar",
          "PS Cantt Jalandhar",
          "PS Model Town Jalandhar",
          "PS Rama Mandi",
          "PS Basti Bawa Khel",
        ],
      },
      {
        district: "Bathinda",
        policeStations: [
          "PS Kotwali Bathinda",
          "PS Civil Lines Bathinda",
          "PS Cantt Bathinda",
          "PS Sadar Bathinda",
          "PS Maur",
          "PS Talwandi Sabo",
          "PS Rampura Phul",
        ],
      },
      {
        district: "Rupnagar (Ropar)",
        policeStations: [
          "PS City Rupnagar",
          "PS Sadar Rupnagar",
          "PS Anandpur Sahib",
          "PS Chamkaur Sahib",
          "PS Morinda",
          "PS Nurpur Bedi",
        ],
      },
      {
        district: "Fatehgarh Sahib",
        policeStations: [
          "PS Sirhind",
          "PS Fatehgarh Sahib",
          "PS Mandi Gobindgarh",
          "PS Amloh",
          "PS Khamanon",
          "PS Bassi Pathana",
        ],
      },
    ],
  },
  {
    state: "Chandigarh",
    districts: [
      {
        district: "Chandigarh",
        policeStations: [
          "PS Sector 3 Chandigarh",
          "PS Sector 11 Chandigarh",
          "PS Sector 17 Chandigarh",
          "PS Sector 19 Chandigarh",
          "PS Sector 26 Chandigarh",
          "PS Sector 31 Chandigarh",
          "PS Sector 34 Chandigarh",
          "PS Sector 36 Chandigarh",
          "PS Sector 39 Chandigarh",
          "PS Industrial Area Chandigarh",
          "PS IT Park Chandigarh",
          "PS Manimajra",
          "PS Maloya",
          "PS Mauli Jagran",
          "PS Cyber Crime Chandigarh",
          "PS Women Chandigarh",
        ],
      },
    ],
  },
  {
    state: "Uttar Pradesh",
    districts: [
      {
        district: "Gautam Buddha Nagar (Noida)",
        policeStations: [
          "PS Sector 20 Noida",
          "PS Sector 24 Noida",
          "PS Sector 39 Noida",
          "PS Sector 58 Noida",
          "PS Sector 49 Noida",
          "PS Sector 126 Noida",
          "PS Sector 142 Noida",
          "PS Expressway Noida",
          "PS Phase 2 Noida",
          "PS Phase 3 Noida",
          "PS Greater Noida",
          "PS Knowledge Park",
          "PS Surajpur",
          "PS Kasna",
          "PS Beta 2 Greater Noida",
          "PS Dadri",
          "PS Ecotech 3",
        ],
      },
      {
        district: "Ghaziabad",
        policeStations: [
          "PS Kotwali Ghaziabad",
          "PS Sihani Gate",
          "PS Kavi Nagar",
          "PS Indirapuram",
          "PS Sahibabad",
          "PS Link Road",
          "PS Vijay Nagar",
          "PS Khoda",
          "PS Loni",
          "PS Loni Border",
          "PS Muradnagar",
          "PS Modinagar",
        ],
      },
      {
        district: "Meerut",
        policeStations: [
          "PS Kotwali Meerut",
          "PS Civil Lines Meerut",
          "PS Nauchandi",
          "PS Medical Meerut",
          "PS Lal Kurti",
          "PS Sadar Bazar Meerut",
          "PS Brahmpuri",
          "PS Partapur",
          "PS Kankerkhera",
        ],
      },
      {
        district: "Agra",
        policeStations: [
          "PS Tajganj",
          "PS Rakabganj",
          "PS Hariparvat",
          "PS Chhatta Agra",
          "PS Kotwali Agra",
          "PS Sadar Agra",
          "PS Sikandra",
          "PS New Agra",
        ],
      },
      {
        district: "Lucknow",
        policeStations: [
          "PS Hazratganj",
          "PS Hussainganj",
          "PS Kaiserbagh",
          "PS Gomti Nagar",
          "PS Mahanagar Lucknow",
          "PS Aliganj Lucknow",
          "PS Indira Nagar",
          "PS Chowk Lucknow",
        ],
      },
      {
        district: "Mathura",
        policeStations: [
          "PS Kotwali Mathura",
          "PS Highway Mathura",
          "PS Vrindavan",
          "PS Govardhan",
          "PS Barsana",
          "PS Chhata Mathura",
          "PS Refinery Mathura",
        ],
      },
      {
        district: "Aligarh",
        policeStations: [
          "PS Kotwali Aligarh",
          "PS Civil Lines Aligarh",
          "PS Banna Devi",
          "PS Gandhi Park",
          "PS Kwarsi",
          "PS Sasni Gate",
        ],
      },
      {
        district: "Saharanpur",
        policeStations: [
          "PS Kotwali Saharanpur",
          "PS Sadar Bazar Saharanpur",
          "PS Janakpuri Saharanpur",
          "PS Deoband",
          "PS Gangoh",
          "PS Nakur",
        ],
      },
      {
        district: "Muzaffarnagar",
        policeStations: [
          "PS Kotwali Muzaffarnagar",
          "PS Civil Lines Muzaffarnagar",
          "PS Nai Mandi",
          "PS Mansoorpur",
          "PS Khatauli",
        ],
      },
    ],
  },
  {
    state: "Rajasthan",
    districts: [
      {
        district: "Jaipur",
        policeStations: [
          "PS Kotwali Jaipur",
          "PS Ashok Nagar Jaipur",
          "PS Manak Chowk",
          "PS Vidhyadhar Nagar",
          "PS Malviya Nagar Jaipur",
          "PS Vaishali Nagar Jaipur",
          "PS Mansarovar Jaipur",
          "PS Sanganer",
        ],
      },
      {
        district: "Alwar",
        policeStations: [
          "PS Kotwali Alwar",
          "PS NEB Alwar",
          "PS Shivaji Park Alwar",
          "PS Aravali Vihar",
          "PS Bhiwadi Phase 1",
          "PS Bhiwadi Phase 3",
          "PS Tijara",
          "PS Behror",
          "PS Neemrana",
        ],
      },
      {
        district: "Bharatpur",
        policeStations: [
          "PS Kotwali Bharatpur",
          "PS Mathura Gate",
          "PS Atal Band",
          "PS Udyog Nagar Bharatpur",
          "PS Deeg",
          "PS Kaman",
        ],
      },
      {
        district: "Jhunjhunu",
        policeStations: [
          "PS Kotwali Jhunjhunu",
          "PS Bagar",
          "PS Chirawa",
          "PS Khetri",
          "PS Nawalgarh",
          "PS Pilani",
        ],
      },
    ],
  },
  {
    state: "Himachal Pradesh",
    districts: [
      {
        district: "Shimla",
        policeStations: [
          "PS Sadar Shimla",
          "PS Boileauganj",
          "PS Chotta Shimla",
          "PS Dhalli",
          "PS New Shimla",
          "PS Theog",
        ],
      },
      {
        district: "Solan",
        policeStations: [
          "PS Sadar Solan",
          "PS Dharampur Solan",
          "PS Kasauli",
          "PS Baddi",
          "PS Barotiwala",
          "PS Nalagarh",
          "PS Parwanoo",
        ],
      },
      {
        district: "Sirmaur",
        policeStations: [
          "PS Nahan",
          "PS Paonta Sahib",
          "PS Majra",
          "PS Renuka Ji",
          "PS Rajgarh",
        ],
      },
    ],
  },
  {
    state: "Uttarakhand",
    districts: [
      {
        district: "Dehradun",
        policeStations: [
          "PS Kotwali Dehradun",
          "PS Dalanwala",
          "PS Cantt Dehradun",
          "PS Vasant Vihar Dehradun",
          "PS Nehru Colony",
          "PS Raipur Dehradun",
          "PS Patel Nagar Dehradun",
          "PS Rishikesh",
          "PS Mussoorie",
        ],
      },
      {
        district: "Haridwar",
        policeStations: [
          "PS Kotwali Haridwar",
          "PS Jwalapur",
          "PS Kankhal",
          "PS Ranipur",
          "PS Bahadrabad",
          "PS Roorkee Civil Lines",
          "PS Gangnahar",
        ],
      },
    ],
  },
  {
    state: "Bihar",
    districts: [
      {
        district: "Patna",
        policeStations: [
          "PS Kotwali Patna",
          "PS Gandhi Maidan",
          "PS Kankarbagh",
          "PS Shastri Nagar Patna",
          "PS Patliputra",
          "PS Danapur",
        ],
      },
      {
        district: "Gaya",
        policeStations: [
          "PS Civil Lines Gaya",
          "PS Kotwali Gaya",
          "PS Rampur Gaya",
          "PS Bodh Gaya",
        ],
      },
    ],
  },
  {
    state: "Madhya Pradesh",
    districts: [
      {
        district: "Bhopal",
        policeStations: [
          "PS TT Nagar",
          "PS MP Nagar",
          "PS Habibganj",
          "PS Govindpura",
          "PS Kotwali Bhopal",
        ],
      },
      {
        district: "Indore",
        policeStations: [
          "PS Palasia",
          "PS Tukoganj",
          "PS Vijay Nagar Indore",
          "PS Sarafa",
          "PS Bhanwarkuan",
        ],
      },
    ],
  },
  {
    state: "Maharashtra",
    districts: [
      {
        district: "Mumbai City",
        policeStations: [
          "PS Colaba",
          "PS Marine Drive",
          "PS Azad Maidan",
          "PS Cuffe Parade",
          "PS Malabar Hill",
        ],
      },
      {
        district: "Mumbai Suburban",
        policeStations: [
          "PS Bandra",
          "PS Andheri",
          "PS Juhu",
          "PS Kurla",
          "PS Borivali",
          "PS Kandivali",
        ],
      },
      {
        district: "Pune",
        policeStations: [
          "PS Shivajinagar",
          "PS Deccan Gymkhana",
          "PS Kothrud",
          "PS Hinjewadi",
          "PS Hadapsar",
        ],
      },
    ],
  },
  {
    state: "Gujarat",
    districts: [
      {
        district: "Ahmedabad",
        policeStations: [
          "PS Navrangpura",
          "PS Satellite",
          "PS Ellisbridge",
          "PS Vastrapur",
          "PS Karanj",
        ],
      },
      {
        district: "Surat",
        policeStations: [
          "PS Umra",
          "PS Athwa Lines",
          "PS Katargam",
          "PS Varachha",
          "PS Adajan",
        ],
      },
    ],
  },
];

// Helper functions for easy querying
export function getStatesList(): string[] {
  return JURISDICTION_DATA.map((item) => item.state);
}

export function getDistrictsForState(stateName: string): string[] {
  const stateData = JURISDICTION_DATA.find(
    (item) => item.state.toLowerCase() === stateName.toLowerCase()
  );
  if (!stateData) return [];
  return stateData.districts.map((d) => d.district);
}

export function getPoliceStationsForDistrict(
  stateName: string,
  districtName: string
): string[] {
  const stateData = JURISDICTION_DATA.find(
    (item) => item.state.toLowerCase() === stateName.toLowerCase()
  );
  if (!stateData) return [];
  const districtData = stateData.districts.find(
    (d) => d.district.toLowerCase() === districtName.toLowerCase()
  );
  if (!districtData) return [];
  return districtData.policeStations;
}
