import { ComplaintItem, GeneralDiaryItem, UserSession, HistoricalFirItem } from "@/types";

export const DEMO_USERS: UserSession[] = [
  {
    id: "usr_sho_1",
    pno: "04291882",
    name: "Inspector Rajesh Kumar",
    rank: "INSPECTOR",
    rankDisplay: "Inspector / SHO",
    role: "SHO",
    roleDisplay: "Station House Officer",
    stationName: "PS City Thanesar",
    stationCode: "HAR-KKR-PS-01",
    district: "Kurukshetra",
    avatarUrl: "/avatars/sho.png",
  },
  {
    id: "usr_eo_1",
    pno: "07182930",
    name: "Sub-Inspector Vikram Singh",
    rank: "SUB_INSPECTOR",
    rankDisplay: "Sub-Inspector",
    role: "ENQUIRY_OFFICER",
    roleDisplay: "Enquiry Officer (EO 1)",
    stationName: "PS City Thanesar",
    stationCode: "HAR-KKR-PS-01",
    district: "Kurukshetra",
  },
  {
    id: "usr_eo_2",
    pno: "06281923",
    name: "ASI Ramesh Chander",
    rank: "ASSISTANT_SUB_INSPECTOR",
    rankDisplay: "ASI",
    role: "ENQUIRY_OFFICER",
    roleDisplay: "Enquiry Officer (EO 2)",
    stationName: "PS City Thanesar",
    stationCode: "HAR-KKR-PS-01",
    district: "Kurukshetra",
  },
  {
    id: "usr_duty_1",
    pno: "09384712",
    name: "ASI Surender Pal",
    rank: "ASSISTANT_SUB_INSPECTOR",
    rankDisplay: "ASI",
    role: "DUTY_OFFICER",
    roleDisplay: "Duty Officer (Counter)",
    stationName: "PS City Thanesar",
    stationCode: "HAR-KKR-PS-01",
    district: "Kurukshetra",
  },
  {
    id: "usr_mhc_1",
    pno: "05192834",
    name: "HC Devinder Kumar",
    rank: "HEAD_CONSTABLE",
    rankDisplay: "Head Constable",
    role: "MHC_GD_INCHARGE",
    roleDisplay: "Moharrir Head Constable (MHC)",
    stationName: "PS City Thanesar",
    stationCode: "HAR-KKR-PS-01",
    district: "Kurukshetra",
  },
  {
    id: "usr_dsp_1",
    pno: "02198301",
    name: "Amit Dahiya, HPS",
    rank: "DEPUTY_SP",
    rankDisplay: "Deputy SP (Sub-Division)",
    role: "DSP_SUBDIV",
    roleDisplay: "DSP Sub-Division",
    stationName: "Sub-Divisional Police Office Thanesar",
    stationCode: "HAR-KKR-SD-01",
    district: "Kurukshetra",
  },
];

export const MOCK_POLICE_STATIONS = [
  "PS City Thanesar",
  "PS Sadar Thanesar",
  "PS Krishna Gate",
  "PS Shahabad",
  "PS Pehowa",
  "PS Ladwa",
  "PS Cyber Crime Kurukshetra",
  "PS Women Kurukshetra",
];

export const MOCK_ENQUIRY_OFFICERS = [
  {
    id: "eo_1",
    name: "SI Vikram Singh",
    pno: "07182930",
    beltNumber: "742/KKR",
    phone: "9812034567",
    rank: "SI",
    activeCases: 4,
    rosterDuty: "Day Investigation & Spot Inquiry Duty",
    shift: "Day Shift (08:00 - 20:00)",
    availability: "Available" as const,
    specialization: "Cyber, Cheating & Financial Crimes",
    beatZone: "Sector 7 & Urban Estate Beat",
  },
  {
    id: "eo_2",
    name: "ASI Ramesh Chander",
    pno: "06281923",
    beltNumber: "628/KKR",
    phone: "9812045678",
    rank: "ASI",
    activeCases: 3,
    rosterDuty: "Land & Property Dispute Verification Duty",
    shift: "Day Shift (09:00 - 18:00)",
    availability: "Available" as const,
    specialization: "Revenue & Boundary Disputes",
    beatZone: "Mirzapur & Rural Agricultural Beat",
  },
  {
    id: "eo_3",
    name: "ASI Surender Pal",
    pno: "09384712",
    beltNumber: "938/KKR",
    phone: "9812056789",
    rank: "ASI",
    activeCases: 5,
    rosterDuty: "Station Duty Officer & General Inquiry",
    shift: "General Shift (08:00 - 16:00)",
    availability: "On Duty" as const,
    specialization: "Theft, Burglary & Public Nuisance",
    beatZone: "Railway Road & Main Bazaar Beat",
  },
  {
    id: "eo_4",
    name: "SI Meenakshi Sharma",
    pno: "08234190",
    beltNumber: "823/KKR",
    phone: "9812067890",
    rank: "SI (Women Desk)",
    activeCases: 2,
    rosterDuty: "Women Helpdesk & Family Dispute Counseling",
    shift: "Day Shift (09:00 - 17:00)",
    availability: "Available" as const,
    specialization: "Domestic Violence & Matrimonial Conciliation",
    beatZone: "City Thanesar Women Safety Desk",
  },
  {
    id: "eo_5",
    name: "HC Satish Kumar",
    pno: "05128394",
    beltNumber: "512/KKR",
    phone: "9812078901",
    rank: "Head Constable",
    activeCases: 6,
    rosterDuty: "Court Orderly & Summons Service Duty",
    shift: "Court Hours (10:00 - 16:30)",
    availability: "In Court" as const,
    specialization: "Civil Tenancy & Recovery Notices",
    beatZone: "District Courts Complex",
  },
];

export const MOCK_COMPLAINTS: ComplaintItem[] = [
  {
    id: "cmp_001",
    complaintNumber: "HAR-KKR-2026-CMP-00482",
    source: "CM_WINDOW_HARYANA",
    category: "FINANCIAL_FRAUD_CHEATING",
    categoryDisplay: "Financial Fraud / Cheating",
    priority: "CM_WINDOW_VIP",
    status: "ENQUIRY_IN_PROGRESS",
    incidentDate: "2026-09-28",
    incidentPlace: "Sector 7 Market, Kurukshetra",
    incidentLandmark: "Opposite SBI Main Branch",
    incidentDetails:
      "Complainant transferred Rs. 4,75,000 on pretext of providing government job in Haryana Irrigation Dept. Suspect provided fabricated appointment letter with fake department stamps.",
    complainantName: "Kuldeep Sharma",
    complainantFatherSpouse: "Late Sh. Ram Kishan Sharma",
    complainantGender: "MALE",
    complainantAge: 32,
    complainantMobile: "9812044812",
    complainantAltPhone: "9416033910",
    complainantAddress: "H.No. 142, Street 3, Urban Estate, Sector 7",
    complainantCity: "Kurukshetra",
    complainantDistrict: "Kurukshetra",
    accusedList: [
      {
        name: "Ravinder Sandhu",
        alias: "Ravi",
        fatherName: "Banta Singh",
        address: "Village Umri, District Kurukshetra",
        phone: "9896011223",
        relationWithComplainant: "Acquaintance via broker",
      },
    ],
    policeStation: "PS City Thanesar",
    district: "Kurukshetra",
    registeredBy: "ASI Surender Pal",
    assignedEoName: "SI Vikram Singh",
    assignedEoPno: "07182930",
    assignedEoRank: "SI",
    assignedAt: "2026-09-29T10:30:00Z",
    daysPending: 4,
    targetResolutionDate: "2026-10-14",
    createdAt: "2026-09-29T09:15:00Z",
    updatedAt: "2026-10-02T16:20:00Z",
  },
  {
    id: "cmp_002",
    complaintNumber: "HAR-KKR-2026-CMP-00483",
    source: "WALK_IN_STATION",
    category: "LAND_PROPERTY_DISPUTE",
    categoryDisplay: "Land / Boundary Dispute",
    priority: "ROUTINE",
    status: "REPORT_SUBMITTED",
    incidentDate: "2026-09-25",
    incidentPlace: "Agricultural Land, Khasra No. 14//8, Village Mirzapur",
    incidentLandmark: "Near Canal Bridge",
    incidentDetails:
      "Dispute regarding construction of boundary wall and blocking common water passage between agricultural fields. Allegations of verbal abuse and threats.",
    complainantName: "Baldev Singh",
    complainantFatherSpouse: "Sardar Gurnam Singh",
    complainantGender: "MALE",
    complainantAge: 58,
    complainantMobile: "9466088211",
    complainantAddress: "Village Mirzapur, Post Office Thanesar",
    complainantCity: "Kurukshetra",
    complainantDistrict: "Kurukshetra",
    accusedList: [
      {
        name: "Joginder Singh",
        fatherName: "Sardar Tarsem Singh",
        address: "Village Mirzapur",
        relationWithComplainant: "Neighboring Field Owner",
      },
    ],
    policeStation: "PS City Thanesar",
    district: "Kurukshetra",
    registeredBy: "ASI Surender Pal",
    assignedEoName: "ASI Ramesh Chander",
    assignedEoPno: "06281923",
    assignedEoRank: "ASI",
    assignedAt: "2026-09-26T11:00:00Z",
    daysPending: 7,
    targetResolutionDate: "2026-10-10",
    createdAt: "2026-09-26T10:00:00Z",
    updatedAt: "2026-10-02T14:45:00Z",
  },
  {
    id: "cmp_003",
    complaintNumber: "HAR-KKR-2026-CMP-00484",
    source: "EMERGENCY_112",
    category: "PHYSICAL_ASSAULT_AFFRAY",
    categoryDisplay: "Physical Assault / Affray",
    priority: "URGENT",
    status: "RECOMMENDED_FOR_FIR",
    incidentDate: "2026-10-01",
    incidentPlace: "Railway Road Chowk, Thanesar",
    incidentLandmark: "Near Hotel Shivalik",
    incidentDetails:
      "Shopkeeper beaten by four youths wielding iron rods following argument over parking. MLR conducted at LNJP Civil Hospital confirming blunt trauma fracture on left arm.",
    complainantName: "Mohit Verma",
    complainantFatherSpouse: "Sh. Suresh Verma",
    complainantGender: "MALE",
    complainantAge: 27,
    complainantMobile: "9812977431",
    complainantAddress: "Shop No. 12, Main Bazaar, Thanesar",
    complainantCity: "Kurukshetra",
    complainantDistrict: "Kurukshetra",
    accusedList: [
      {
        name: "Vikas alias Vicky",
        address: "Near Old Bus Stand",
        phone: "9813009944",
      },
      {
        name: "3 Unidentified accomplices",
      },
    ],
    policeStation: "PS City Thanesar",
    district: "Kurukshetra",
    registeredBy: "ASI Surender Pal",
    assignedEoName: "SI Vikram Singh",
    assignedEoPno: "07182930",
    assignedEoRank: "SI",
    assignedAt: "2026-10-01T21:30:00Z",
    daysPending: 2,
    targetResolutionDate: "2026-10-05",
    createdAt: "2026-10-01T21:00:00Z",
    updatedAt: "2026-10-03T09:30:00Z",
  },
  {
    id: "cmp_004",
    complaintNumber: "HAR-KKR-2026-CMP-00485",
    source: "WALK_IN_STATION",
    category: "DOMESTIC_VIOLENCE_DOWRY",
    categoryDisplay: "Domestic Dispute / Dowry Harassment",
    priority: "HIGH_PRIORITY" as any,
    status: "ASSIGNED_TO_EO",
    incidentDate: "2026-09-30",
    incidentPlace: "Mohalla Kalyan Nagar, Thanesar",
    incidentLandmark: "Near Arya Samaj Mandir",
    incidentDetails:
      "Cruelty and harassment by in-laws demanding additional cash of Rs. 3 Lakh and vehicle. Complainant turned out of matrimonial house.",
    complainantName: "Pooja Rani",
    complainantFatherSpouse: "Deepak Kumar (Husband)",
    complainantGender: "FEMALE",
    complainantAge: 29,
    complainantMobile: "9896555123",
    complainantAddress: "C/o Sh. Rameshwar Dass, Kalyan Nagar",
    complainantCity: "Kurukshetra",
    complainantDistrict: "Kurukshetra",
    accusedList: [
      {
        name: "Deepak Kumar",
        relationWithComplainant: "Husband",
        address: "Model Town, Pehowa",
      },
      {
        name: "Kanta Devi",
        relationWithComplainant: "Mother-in-law",
        address: "Model Town, Pehowa",
      },
    ],
    policeStation: "PS City Thanesar",
    district: "Kurukshetra",
    registeredBy: "ASI Surender Pal",
    assignedEoName: "SI Meenakshi Sharma",
    assignedEoPno: "08234190",
    assignedEoRank: "SI (Women Desk)",
    assignedAt: "2026-10-02T11:00:00Z",
    daysPending: 1,
    targetResolutionDate: "2026-10-17",
    createdAt: "2026-10-02T10:15:00Z",
    updatedAt: "2026-10-02T11:00:00Z",
  },
  {
    id: "cmp_005",
    complaintNumber: "HAR-KKR-2026-CMP-00486",
    source: "CITIZEN_PORTAL_HARPATH",
    category: "CYBER_CRIME",
    categoryDisplay: "Cyber Crime / Online Fraud",
    priority: "ROUTINE",
    status: "REGISTERED",
    incidentDate: "2026-10-02",
    incidentPlace: "Cyber Space / Victim residence in DD Colony",
    incidentLandmark: "DD Colony Gate 1",
    incidentDetails:
      "Received fraudulent APK file on WhatsApp promising electricity bill rebate. Bank account debited for Rs. 84,200 via 3 unauthorized UPI transactions.",
    complainantName: "Dr. Ashok Mehta",
    complainantFatherSpouse: "Late Sh. K.L. Mehta",
    complainantGender: "MALE",
    complainantAge: 62,
    complainantMobile: "9416248901",
    complainantAddress: "Kothi No. 89, DD Colony",
    complainantCity: "Kurukshetra",
    complainantDistrict: "Kurukshetra",
    accusedList: [
      {
        name: "Unknown Cyber Fraudster",
        phone: "7829103948",
      },
    ],
    policeStation: "PS City Thanesar",
    district: "Kurukshetra",
    registeredBy: "ASI Surender Pal",
    daysPending: 1,
    createdAt: "2026-10-03T08:30:00Z",
    updatedAt: "2026-10-03T08:30:00Z",
  },
  {
    id: "cmp_006",
    complaintNumber: "HAR-KKR-2026-CMP-00470",
    source: "WALK_IN_STATION",
    category: "LAND_PROPERTY_DISPUTE",
    categoryDisplay: "Civil Dispute / Tenancy",
    priority: "ROUTINE",
    status: "DISPOSED_CIVIL_NATURE",
    incidentDate: "2026-09-12",
    incidentPlace: "Salarpur Road Market",
    incidentLandmark: "Near Old Grain Market",
    incidentDetails:
      "Landlord-tenant dispute over non-payment of rent for 4 months and refusal to vacate commercial premises after lease expiry.",
    complainantName: "Satish Bansal",
    complainantFatherSpouse: "Sh. Om Prakash Bansal",
    complainantGender: "MALE",
    complainantAge: 51,
    complainantMobile: "9812001199",
    complainantAddress: "Bansal Building, Salarpur Road",
    complainantCity: "Kurukshetra",
    complainantDistrict: "Kurukshetra",
    accusedList: [
      {
        name: "Rajan Chawla",
        relationWithComplainant: "Tenant",
        address: "Shop No. 4, Salarpur Road",
      },
    ],
    policeStation: "PS City Thanesar",
    district: "Kurukshetra",
    registeredBy: "ASI Surender Pal",
    assignedEoName: "HC Satish Kumar",
    assignedEoPno: "05128394",
    assignedEoRank: "Head Constable",
    assignedAt: "2026-09-13T10:00:00Z",
    daysPending: 15,
    createdAt: "2026-09-13T09:00:00Z",
    updatedAt: "2026-09-28T17:00:00Z",
  },
];

export const MOCK_GD_ENTRIES: GeneralDiaryItem[] = [
  {
    id: "gd_001",
    gdNumber: "GD-2026-10-03-001",
    sequencePerDay: 1,
    entryTime: "00:05",
    entryDate: "2026-10-03",
    entryType: "OPENING_OF_DIARY",
    entryTypeDisplay: "Opening of Daily Roznamcha",
    subject: "Opening of Daily Roznamcha Aam for 03-Oct-2026",
    narrative:
      "At 00:05 hours, Daily General Diary (Roznamcha Aam) of Police Station City Thanesar opened in accordance with Punjab Police Rules 22.48. Sentry duty handed over to Constable Vikas No. 892/KKR. Arms, ammunition, lock-up prisoners (2 males in custody) and Malkhana seals verified and intact.",
    policeStation: "PS City Thanesar",
    loggedByOfficer: "HC Devinder Kumar",
    loggedByPno: "05192834",
    isLocked: true,
  },
  {
    id: "gd_002",
    gdNumber: "GD-2026-10-03-002",
    sequencePerDay: 2,
    entryTime: "02:30",
    entryDate: "2026-10-03",
    entryType: "PATROL_DEPARTURE_RETURN",
    entryTypeDisplay: "Night Domination Return",
    subject: "Return of Night Domination PCR Van 04",
    narrative:
      "PCR Van 04 (In-charge ASI Mahipal with Driver Constable Sunil) returned after completing night domination patrol across Railway Road, Pipli Road and Brahma Sarovar outer perimeter. No untoward incident noticed. 18 suspicious vehicles checked; 2 challaned for high-beam/tint.",
    policeStation: "PS City Thanesar",
    loggedByOfficer: "HC Devinder Kumar",
    loggedByPno: "05192834",
    isLocked: true,
  },
  {
    id: "gd_003",
    gdNumber: "GD-2026-10-03-003",
    sequencePerDay: 3,
    entryTime: "08:35",
    entryDate: "2026-10-03",
    entryType: "COMPLAINT_RECEIPT",
    entryTypeDisplay: "Complaint Intake",
    subject: "Receipt of Cyber Fraud Complaint - Dr. Ashok Mehta",
    narrative:
      "Dr. Ashok Mehta s/o Late Sh. K.L. Mehta r/o DD Colony Kurukshetra submitted a written complaint regarding online banking fraud of Rs. 84,200/- via APK phishing link. Complaint registered in CMS under CMP No. HAR-KKR-2026-CMP-00486 and placed before SHO for assignment.",
    policeStation: "PS City Thanesar",
    loggedByOfficer: "ASI Surender Pal",
    loggedByPno: "09384712",
    relatedComplaintNumber: "HAR-KKR-2026-CMP-00486",
    isLocked: true,
  },
  {
    id: "gd_004",
    gdNumber: "GD-2026-10-03-004",
    sequencePerDay: 4,
    entryTime: "09:45",
    entryDate: "2026-10-03",
    entryType: "OFFICER_DEPARTURE",
    entryTypeDisplay: "Officer Departure",
    subject: "Departure of SI Vikram Singh for Spot Verification",
    narrative:
      "Sub-Inspector Vikram Singh departed along with Constable Naresh No. 412 on government motorcycle for spot verification and witness statements in CMP No. HAR-KKR-2026-CMP-00482 at Sector 7 Kurukshetra.",
    policeStation: "PS City Thanesar",
    loggedByOfficer: "HC Devinder Kumar",
    loggedByPno: "05192834",
    relatedComplaintNumber: "HAR-KKR-2026-CMP-00482",
    isLocked: true,
  },
];

export const MOCK_HISTORICAL_FIRS: HistoricalFirItem[] = [
  {
    id: "fir_2025_182",
    firNumber: "FIR No. 182/2025",
    policeStation: "PS City Thanesar",
    district: "Kurukshetra",
    registrationDate: "2025-11-14",
    sectionsOfLaw: "Section 323, 341, 506, 34 IPC (Voluntarily causing hurt & criminal intimidation)",
    complainantName: "Mohit Verma",
    complainantPhone: "9812977431",
    accusedNames: ["Vikas alias Vicky", "Suresh Kumar", "Ravi Sandhu"],
    accusedPhones: ["9813009944", "9896011223"],
    status: "CHARGESHEETED",
    incidentBrief: "Altercation and physical scuffle at Old Bus Stand Chowk. Accused chargesheeted before CJM Kurukshetra; trial pending.",
  },
  {
    id: "fir_2026_044",
    firNumber: "FIR No. 44/2026",
    policeStation: "PS City Thanesar",
    district: "Kurukshetra",
    registrationDate: "2026-03-22",
    sectionsOfLaw: "Section 318(4) BNS (Cheating) & Sec 66D IT Act",
    complainantName: "Sunil Grover",
    accusedNames: ["Ravinder Sandhu", "Amit Bansal"],
    accusedPhones: ["9896011223"],
    status: "UNDER_INVESTIGATION",
    incidentBrief: "Fraudulent recruitment scam regarding railway clerk employment.",
  },
  {
    id: "fir_2024_089",
    firNumber: "FIR No. 89/2024",
    policeStation: "PS Sadar Thanesar",
    district: "Kurukshetra",
    registrationDate: "2024-06-18",
    sectionsOfLaw: "Section 147, 149, 323, 447, 506 IPC (Unlawful assembly & land trespass)",
    complainantName: "Joginder Singh",
    complainantPhone: "9466088211",
    accusedNames: ["Baldev Singh", "Kuldeep Singh"],
    accusedPhones: ["9466088211", "9813088772"],
    status: "PENDING_TRIAL",
    incidentBrief: "Cross-fight over irrigation canal passage and agricultural land boundary in Mirzapur village.",
  },
  {
    id: "fir_2025_310",
    firNumber: "FIR No. 310/2025",
    policeStation: "PS City Thanesar",
    district: "Kurukshetra",
    registrationDate: "2025-12-05",
    sectionsOfLaw: "Section 498A, 406, 323 IPC (Cruelty by husband/in-laws & breach of trust of stridhan)",
    complainantName: "Pooja Rani",
    complainantPhone: "9896555123",
    accusedNames: ["Deepak Kumar", "Kanta Devi"],
    status: "PENDING_TRIAL",
    incidentBrief: "Marital cruelty and dowry harassment chargesheeted before Judicial Magistrate 1st Class Kurukshetra.",
  },
];
