// src/lib/pcActSectionsData.ts
// Comprehensive Sections, Sub-sections, Clauses, Provisos & Explanations
// for The Prevention of Corruption Act, 1988 (Act No. 49 of 1988 as amended)
// Total 190 complete statutory items with precise Hindi legal titles.

import type { CCTNSSectionItem } from "./cctnsActsData";

export const PC_ACT_1988_SECTIONS: CCTNSSectionItem[] = [
  { sectionNumber: "1", title: "अधिनियम का संक्षिप्त नाम और विस्तार।" },
  { sectionNumber: "1(1)", title: "अधिनियम का नाम Prevention of Corruption Act, 1988।" },
  { sectionNumber: "1(2)", title: "पूरे भारत और भारत के बाहर भारतीय नागरिकों पर लागू होना।" },

  { sectionNumber: "2", title: "अधिनियम में प्रयुक्त शब्दों की परिभाषाएँ।" },
  { sectionNumber: "2(a)", title: "Election: निर्धारित सार्वजनिक संस्थाओं के सदस्यों के चयन का निर्वाचन।" },
  { sectionNumber: "2(aa)", title: "Prescribed: अधिनियम के नियमों द्वारा निर्धारित।" },
  { sectionNumber: "2(b)", title: "Public Duty: ऐसा कर्तव्य जिसमें राज्य, जनता या समुदाय का हित हो।" },
  { sectionNumber: "2(b) Explanation", title: "State में निर्धारित सरकारी निगम, निकाय और सरकारी कंपनी भी शामिल।" },
  { sectionNumber: "2(c)", title: "Public Servant: लोक सेवक की परिभाषा।" },
  { sectionNumber: "2(c)(i)", title: "सरकारी सेवा, वेतन या सार्वजनिक कर्तव्य के लिए सरकारी पारिश्रमिक पाने वाला व्यक्ति।" },
  { sectionNumber: "2(c)(ii)", title: "स्थानीय प्राधिकारी की सेवा या वेतन में कार्यरत व्यक्ति।" },
  { sectionNumber: "2(c)(iii)", title: "निर्धारित सरकारी निगम, सहायता प्राप्त निकाय या सरकारी कंपनी का कर्मचारी।" },
  { sectionNumber: "2(c)(iv)", title: "न्यायाधीश और कानून द्वारा न्यायनिर्णय के लिए अधिकृत व्यक्ति।" },
  { sectionNumber: "2(c)(v)", title: "न्यायालय द्वारा न्याय प्रशासन संबंधी काम के लिए अधिकृत व्यक्ति।" },
  { sectionNumber: "2(c)(vi)", title: "न्यायालय या सक्षम सार्वजनिक प्राधिकारी द्वारा नियुक्त मध्यस्थ या निर्णयकर्ता।" },
  { sectionNumber: "2(c)(vii)", title: "मतदाता सूची या निर्वाचन संबंधी कार्य के लिए अधिकृत पदधारक।" },
  { sectionNumber: "2(c)(viii)", title: "पद के कारण सार्वजनिक कर्तव्य निभाने के लिए अधिकृत या बाध्य व्यक्ति।" },
  { sectionNumber: "2(c)(ix)", title: "निर्धारित सरकारी सहायता प्राप्त सहकारी समिति का अध्यक्ष, सचिव या अन्य पदाधिकारी।" },
  { sectionNumber: "2(c)(x)", title: "सेवा आयोग, बोर्ड या उसकी चयन समिति का निर्धारित सदस्य अथवा कर्मचारी।" },
  { sectionNumber: "2(c)(xi)", title: "विश्वविद्यालय के निर्धारित पदाधिकारी, शिक्षक, कर्मचारी और परीक्षा संबंधी कार्यकर्ता।" },
  { sectionNumber: "2(c)(xii)", title: "सरकारी सहायता प्राप्त शिक्षण, वैज्ञानिक, सामाजिक, सांस्कृतिक या अन्य संस्था का पदाधिकारी अथवा कर्मचारी।" },
  { sectionNumber: "2(d)", title: "Undue Advantage: वैध पारिश्रमिक के अतिरिक्त किसी प्रकार का अनुचित लाभ।" },
  { sectionNumber: "2(d) Explanation (a)", title: "Gratification केवल धन या धन में आँके जाने वाले लाभ तक सीमित नहीं।" },
  { sectionNumber: "2(d) Explanation (b)", title: "Legal Remuneration में अधिकृत रूप से प्राप्त करने योग्य सभी पारिश्रमिक शामिल।" },
  { sectionNumber: "2 Explanation 1", title: "निर्धारित श्रेणियों के व्यक्ति सरकारी नियुक्ति न होने पर भी लोक सेवक।" },
  { sectionNumber: "2 Explanation 2", title: "पद धारण करने में कानूनी दोष होने पर भी वास्तविक लोक सेवक शामिल।" },

  { sectionNumber: "3", title: "विशेष न्यायाधीश नियुक्त करने की शक्ति।" },
  { sectionNumber: "3(1)", title: "केंद्र या राज्य सरकार द्वारा विशेष न्यायाधीश नियुक्त करना।" },
  { sectionNumber: "3(1)(a)", title: "अधिनियम के अंतर्गत दंडनीय अपराधों का विचारण।" },
  { sectionNumber: "3(1)(b)", title: "संबंधित षड्यंत्र, प्रयास और दुष्प्रेरण का विचारण।" },
  { sectionNumber: "3(2)", title: "विशेष न्यायाधीश की नियुक्ति के लिए न्यायिक योग्यता।" },

  { sectionNumber: "4", title: "विशेष न्यायाधीश द्वारा विचारण किए जाने वाले मामले।" },
  { sectionNumber: "4(1)", title: "निर्धारित अपराधों का केवल विशेष न्यायाधीश द्वारा विचारण।" },
  { sectionNumber: "4(2)", title: "क्षेत्र या विशेष मामले के अनुसार सक्षम विशेष न्यायाधीश।" },
  { sectionNumber: "4(3)", title: "उसी विचारण में संबंधित अन्य अपराधों का विचारण।" },
  { sectionNumber: "4(4)", title: "यथासंभव दैनिक सुनवाई और दो वर्ष में विचारण पूरा करने का प्रयास।" },
  { sectionNumber: "4(4) First Proviso", title: "दो वर्ष में विचारण पूरा न होने के कारण दर्ज करना।" },
  { sectionNumber: "4(4) Second Proviso", title: "कारण दर्ज करके अवधि बढ़ाना; सामान्यतः कुल चार वर्ष की सीमा।" },

  { sectionNumber: "5", title: "विशेष न्यायाधीश की प्रक्रिया और शक्तियाँ।" },
  { sectionNumber: "5(1)", title: "सीधे संज्ञान लेना और निर्धारित वारंट-मामला प्रक्रिया अपनाना।" },
  { sectionNumber: "5(2)", title: "पूर्ण और सत्य खुलासा करने की शर्त पर संबंधित व्यक्ति को क्षमादान।" },
  { sectionNumber: "5(3)", title: "असंगत न होने तक आपराधिक प्रक्रिया लागू होना और विशेष न्यायालय की स्थिति।" },
  { sectionNumber: "5(4)", title: "निर्धारित आपराधिक प्रक्रिया प्रावधानों का लागू होना।" },
  { sectionNumber: "5(5)", title: "दोषसिद्धि पर कानून द्वारा अधिकृत दंड देना।" },
  { sectionNumber: "5(6)", title: "संपत्ति संबंधी मामलों में निर्धारित जिला न्यायाधीश की शक्तियाँ प्रयोग करना।" },

  { sectionNumber: "6", title: "संक्षिप्त विचारण की शक्ति।" },
  { sectionNumber: "6(1)", title: "Essential Commodities Act से संबंधित निर्धारित अपराधों का संक्षिप्त विचारण।" },
  { sectionNumber: "6(1) First Proviso", title: "संक्षिप्त विचारण में अधिकतम एक वर्ष का कारावास देना।" },
  { sectionNumber: "6(1) Second Proviso", title: "आवश्यक होने पर सामान्य वारंट-मामला प्रक्रिया से विचारण करना।" },
  { sectionNumber: "6(2)", title: "निर्धारित छोटी सजा वाले संक्षिप्त मामलों में अपील पर प्रतिबंध।" },

  { sectionNumber: "7", title: "लोक सेवक द्वारा रिश्वत या अनुचित लाभ लेने का अपराध।" },
  { sectionNumber: "7(a)", title: "सार्वजनिक कर्तव्य अनुचित या बेईमानी से निभाने अथवा न निभाने के उद्देश्य से लाभ लेना।" },
  { sectionNumber: "7(b)", title: "अनुचित कार्य या कर्तव्य न निभाने के पुरस्कार के रूप में लाभ लेना।" },
  { sectionNumber: "7(c)", title: "अनुचित लाभ की अपेक्षा या परिणामस्वरूप सार्वजनिक कर्तव्य अनुचित ढंग से निभाना।" },
  { sectionNumber: "7 Explanation 1", title: "अनुचित लाभ लेना, स्वीकारना या लेने का प्रयास स्वयं अपराध।" },
  { sectionNumber: "7 Explanation 1 Illustration", title: "नियमित काम समय पर करने के लिए रिश्वत माँगने का उदाहरण।" },
  { sectionNumber: "7 Explanation 2", title: "अनुचित लाभ प्राप्त करने या स्वीकारने का विस्तृत अर्थ।" },
  { sectionNumber: "7 Explanation 2 (i)", title: "पद के दुरुपयोग, प्रभाव या भ्रष्ट माध्यम से अपने अथवा दूसरे के लिए लाभ लेना।" },
  { sectionNumber: "7 Explanation 2 (ii)", title: "लाभ सीधे या तीसरे व्यक्ति के माध्यम से लेने में अंतर नहीं।" },

  { sectionNumber: "7A", title: "लोक सेवक को भ्रष्ट माध्यम या निजी प्रभाव से प्रभावित करने के लिए अनुचित लाभ लेना।" },

  { sectionNumber: "8", title: "लोक सेवक को रिश्वत देने का अपराध।" },
  { sectionNumber: "8(1)", title: "अनुचित लाभ देना या देने का वादा करना।" },
  { sectionNumber: "8(1)(i)", title: "लोक सेवक से सार्वजनिक कर्तव्य अनुचित ढंग से करवाने का उद्देश्य।" },
  { sectionNumber: "8(1)(ii)", title: "अनुचित ढंग से किए गए सार्वजनिक कर्तव्य का पुरस्कार देना।" },
  { sectionNumber: "8(1) First Proviso", title: "मजबूरी में अनुचित लाभ देने की निर्धारित छूट।" },
  { sectionNumber: "8(1) Second Proviso", title: "मजबूरी में दिए लाभ की सात दिन के भीतर जाँच एजेंसी को सूचना।" },
  { sectionNumber: "8(1) Third Proviso", title: "व्यावसायिक संगठन द्वारा अपराध पर जुर्माना।" },
  { sectionNumber: "8(1) Illustration", title: "अन्य बोलीदाताओं पर प्राथमिकता लेकर लाइसेंस पाने के लिए रिश्वत देने का उदाहरण।" },
  { sectionNumber: "8(1) Explanation", title: "लाभ किसे या किस माध्यम से दिया गया, इससे अपराध की प्रकृति नहीं बदलती।" },
  { sectionNumber: "8(2)", title: "जाँच एजेंसी को पहले सूचना देकर जाँच में सहायता के लिए लाभ देने की छूट।" },

  { sectionNumber: "9", title: "व्यावसायिक संगठन द्वारा लोक सेवक को रिश्वत देने का अपराध।" },
  { sectionNumber: "9(1)", title: "संगठन से जुड़े व्यक्ति द्वारा व्यावसायिक उद्देश्य से रिश्वत देने पर संगठन का दायित्व।" },
  { sectionNumber: "9(1)(a)", title: "संगठन के लिए व्यवसाय प्राप्त या बनाए रखना।" },
  { sectionNumber: "9(1)(b)", title: "व्यवसाय में लाभ प्राप्त या बनाए रखना।" },
  { sectionNumber: "9(1) Proviso", title: "पर्याप्त भ्रष्टाचार-रोधी प्रक्रियाएँ लागू होने का बचाव।" },
  { sectionNumber: "9(2)", title: "धारा 8 के कथित अपराध के आधार पर लाभ देने या वादा करने की पहचान।" },
  { sectionNumber: "9(3)", title: "संगठन, व्यवसाय और संबंधित व्यक्ति की परिभाषाएँ।" },
  { sectionNumber: "9(3)(a)", title: "Commercial Organisation: व्यावसायिक संगठन।" },
  { sectionNumber: "9(3)(a)(i)", title: "भारत में निगमित और भारत या विदेश में व्यवसाय करने वाला निकाय।" },
  { sectionNumber: "9(3)(a)(ii)", title: "विदेश में निगमित और भारत में व्यवसाय करने वाला निकाय।" },
  { sectionNumber: "9(3)(a)(iii)", title: "भारत में गठित साझेदारी या व्यक्तियों का संगठन।" },
  { sectionNumber: "9(3)(a)(iv)", title: "विदेश में गठित और भारत में व्यवसाय करने वाली साझेदारी या संस्था।" },
  { sectionNumber: "9(3)(b)", title: "Business में व्यापार, पेशा और सेवा प्रदान करना शामिल।" },
  { sectionNumber: "9(3)(c)", title: "संगठन के लिए या उसकी ओर से सेवा करने वाला संबंधित व्यक्ति।" },
  { sectionNumber: "9(3) Explanation 1", title: "कर्मचारी, एजेंट या सहायक कंपनी होने से सेवा का स्वरूप सीमित नहीं।" },
  { sectionNumber: "9(3) Explanation 2", title: "संबंधित व्यक्ति की पहचान सभी प्रासंगिक परिस्थितियों से करना।" },
  { sectionNumber: "9(3) Explanation 3", title: "कर्मचारी के संगठन की ओर से सेवा करने की खंडनीय धारणा।" },
  { sectionNumber: "9(4)", title: "धारा 7A, 8 और 9 के अपराध संज्ञेय होना।" },
  { sectionNumber: "9(5)", title: "व्यावसायिक संगठनों के लिए केंद्र द्वारा भ्रष्टाचार-रोधी दिशानिर्देश बनाना।" },

  { sectionNumber: "10", title: "व्यावसायिक संगठन के जिम्मेदार अधिकारियों का अपराध संबंधी दायित्व।" },
  { sectionNumber: "10 Explanation", title: "साझेदारी फर्म में Director का अर्थ Partner।" },

  { sectionNumber: "11", title: "संबंधित व्यक्ति से बिना प्रतिफल या अपर्याप्त प्रतिफल पर लोक सेवक द्वारा अनुचित लाभ लेना।" },

  { sectionNumber: "12", title: "अधिनियम के अपराधों के दुष्प्रेरण का दंड।" },

  { sectionNumber: "13", title: "लोक सेवक द्वारा आपराधिक दुराचार।" },
  { sectionNumber: "13(1)", title: "आपराधिक दुराचार के निर्धारित प्रकार।" },
  { sectionNumber: "13(1)(a)", title: "सौंपी गई या नियंत्रणाधीन संपत्ति का बेईमानी से गबन अथवा निजी उपयोग।" },
  { sectionNumber: "13(1)(b)", title: "पदावधि में जानबूझकर अवैध रूप से संपन्न होना।" },
  { sectionNumber: "13(1) Explanation 1", title: "ज्ञात आय से अधिक और असंतोषजनक हिसाब वाली संपत्ति पर अवैध संपन्नता की धारणा।" },
  { sectionNumber: "13(1) Explanation 2", title: "Known Sources of Income का अर्थ वैध स्रोतों से प्राप्त आय।" },
  { sectionNumber: "13(2)", title: "आपराधिक दुराचार का दंड।" },

  { sectionNumber: "14", title: "पूर्व दोषसिद्धि के बाद दोबारा अपराध करने वाले का दंड।" },

  { sectionNumber: "15", title: "धारा 13(1)(a) के अपराध का प्रयास करने का दंड।" },

  { sectionNumber: "16", title: "जुर्माना तय करते समय प्राप्त लाभ या बेहिसाब संपत्ति का मूल्य ध्यान में रखना।" },

  { sectionNumber: "17", title: "अपराधों की जाँच के लिए अधिकृत पुलिस अधिकारी।" },
  { sectionNumber: "17(a)", title: "Delhi Special Police Establishment में निर्धारित न्यूनतम Inspector रैंक।" },
  { sectionNumber: "17(b)", title: "निर्धारित महानगरीय क्षेत्रों में Assistant Commissioner of Police रैंक।" },
  { sectionNumber: "17(c)", title: "अन्य स्थानों पर Deputy Superintendent of Police या समकक्ष रैंक।" },
  { sectionNumber: "17 First Proviso", title: "राज्य द्वारा अधिकृत Inspector को निर्धारित जाँच और गिरफ्तारी की शक्ति।" },
  { sectionNumber: "17 Second Proviso", title: "धारा 13(1)(b) की जाँच के लिए Superintendent of Police स्तर का आदेश।" },

  { sectionNumber: "17A", title: "आधिकारिक सिफारिश या निर्णय से संबंधित जाँच हेतु पूर्व अनुमोदन।" },
  { sectionNumber: "17A(a)", title: "संघ के कार्यों से संबंधित लोक सेवक के लिए केंद्र सरकार का अनुमोदन।" },
  { sectionNumber: "17A(b)", title: "राज्य के कार्यों से संबंधित लोक सेवक के लिए राज्य सरकार का अनुमोदन।" },
  { sectionNumber: "17A(c)", title: "अन्य व्यक्ति के लिए पद से हटाने में सक्षम प्राधिकारी का अनुमोदन।" },
  { sectionNumber: "17A First Proviso", title: "मौके पर रिश्वत लेते या लेने का प्रयास करते पकड़े जाने पर अनुमोदन की आवश्यकता नहीं।" },
  { sectionNumber: "17A Second Proviso", title: "तीन महीने में निर्णय; लिखित कारण से एक अतिरिक्त महीने का विस्तार।" },

  { sectionNumber: "18", title: "बैंक अभिलेखों का निरीक्षण और प्रमाणित प्रतियाँ लेने की शक्ति।" },
  { sectionNumber: "18 Proviso", title: "SP से नीचे के अधिकारी के लिए निर्धारित विशेष प्राधिकरण।" },
  { sectionNumber: "18 Explanation", title: "Bank और Bankers’ Books का संबंधित कानून के अनुसार अर्थ।" },

  { sectionNumber: "18A", title: "अपराध से प्राप्त संपत्ति की कुर्की और जब्ती।" },
  { sectionNumber: "18A(1)", title: "निर्धारित सीमा तक Criminal Law Amendment Ordinance, 1944 लागू होना।" },
  { sectionNumber: "18A(2)", title: "District Judge के संदर्भ को Special Judge के रूप में पढ़ना।" },

  { sectionNumber: "19", title: "अभियोजन के लिए पूर्व स्वीकृति।" },
  { sectionNumber: "19(1)", title: "धारा 7, 11, 13 और 15 के निर्धारित मामलों में संज्ञान से पहले स्वीकृति।" },
  { sectionNumber: "19(1)(a)", title: "निर्धारित केंद्रीय लोक सेवक के लिए केंद्र सरकार की स्वीकृति।" },
  { sectionNumber: "19(1)(b)", title: "निर्धारित राज्य लोक सेवक के लिए राज्य सरकार की स्वीकृति।" },
  { sectionNumber: "19(1)(c)", title: "अन्य लोक सेवक के लिए हटाने में सक्षम प्राधिकारी की स्वीकृति।" },
  { sectionNumber: "19(1) First Proviso", title: "निजी व्यक्ति द्वारा स्वीकृति माँगने की पूर्व शर्तें।" },
  { sectionNumber: "19(1) First Proviso (i)", title: "सक्षम न्यायालय में संबंधित अपराध की शिकायत दाखिल होना।" },
  { sectionNumber: "19(1) First Proviso (ii)", title: "शिकायत खारिज न होना और न्यायालय का स्वीकृति प्राप्त करने का निर्देश।" },
  { sectionNumber: "19(1) Second Proviso", title: "निजी अनुरोध पर स्वीकृति से पहले लोक सेवक को सुनवाई का अवसर।" },
  { sectionNumber: "19(1) Third Proviso", title: "स्वीकृति प्रस्ताव पर तीन महीने में निर्णय का प्रयास।" },
  { sectionNumber: "19(1) Fourth Proviso", title: "कानूनी परामर्श के लिए कारण दर्ज करके एक महीने का विस्तार।" },
  { sectionNumber: "19(1) Fifth Proviso", title: "केंद्र द्वारा अभियोजन स्वीकृति के दिशानिर्देश।" },
  { sectionNumber: "19(1) Explanation", title: "पूर्व पदधारकों का भी संबंधित Public Servant में समावेश।" },
  { sectionNumber: "19(1) Explanation (a)", title: "कथित अपराध वाले पद से हट चुका व्यक्ति।" },
  { sectionNumber: "19(1) Explanation (b)", title: "कथित अपराध वाला पद छोड़कर दूसरा पद धारण करने वाला व्यक्ति।" },
  { sectionNumber: "19(2)", title: "संदेह होने पर अपराध के समय हटाने में सक्षम प्राधिकारी द्वारा स्वीकृति।" },
  { sectionNumber: "19(3)", title: "स्वीकृति की त्रुटि और कार्यवाही पर उसके प्रभाव की सीमाएँ।" },
  { sectionNumber: "19(3)(a)", title: "वास्तविक न्याय-विफलता के बिना निर्णय या सजा उलटना नहीं।" },
  { sectionNumber: "19(3)(b)", title: "वास्तविक न्याय-विफलता के बिना स्वीकृति की त्रुटि पर कार्यवाही रोकना नहीं।" },
  { sectionNumber: "19(3)(c)", title: "अन्य आधारों पर रोक और अंतरिम आदेश के पुनरीक्षण पर निर्धारित प्रतिबंध।" },
  { sectionNumber: "19(4)", title: "आपत्ति पहले उठाई जा सकती थी या नहीं, इस पर विचार करना।" },
  { sectionNumber: "19 Explanation (a)", title: "Error में स्वीकृति देने वाले प्राधिकारी की क्षमता भी शामिल।" },
  { sectionNumber: "19 Explanation (b)", title: "Sanction में निर्धारित प्राधिकारी की पहल या अनुमति की समान शर्तें शामिल।" },

  { sectionNumber: "20", title: "अनुचित लाभ स्वीकारने पर निर्धारित भ्रष्ट उद्देश्य की खंडनीय कानूनी धारणा।" },

  { sectionNumber: "21", title: "अभियुक्त का बचाव पक्ष का सक्षम गवाह होना।" },
  { sectionNumber: "21 Proviso", title: "अभियुक्त के गवाही देने संबंधी सुरक्षा और अपवाद।" },
  { sectionNumber: "21 Proviso (a)", title: "केवल स्वयं के अनुरोध पर अभियुक्त को गवाह बनाना।" },
  { sectionNumber: "21 Proviso (b)", title: "गवाही न देने पर प्रतिकूल टिप्पणी या धारणा नहीं।" },
  { sectionNumber: "21 Proviso (c)", title: "अन्य अपराध या बुरे चरित्र संबंधी सवालों से निर्धारित सुरक्षा।" },
  { sectionNumber: "21 Proviso (c)(i)", title: "अन्य अपराध का प्रमाण वर्तमान अपराध के लिए स्वीकार्य होने का अपवाद।" },
  { sectionNumber: "21 Proviso (c)(ii)", title: "स्वयं अच्छे चरित्र का मुद्दा उठाने या अन्य पक्ष के चरित्र पर आरोप लगाने का अपवाद।" },
  { sectionNumber: "21 Proviso (c)(iii)", title: "सह-अभियुक्त के विरुद्ध गवाही देने का अपवाद।" },

  { sectionNumber: "22", title: "आपराधिक प्रक्रिया का निर्धारित परिवर्तनों के साथ लागू होना।" },
  { sectionNumber: "22(a)", title: "बचाव के गवाहों और दस्तावेजों की लिखित सूची माँगना।" },
  { sectionNumber: "22(b)", title: "केवल पुनरीक्षण आवेदन के कारण सुनवाई स्थगित न करना।" },
  { sectionNumber: "22(c)", title: "कारण दर्ज करके अभियुक्त या वकील की अनुपस्थिति में निर्धारित कार्यवाही।" },
  { sectionNumber: "22(d)", title: "पुनरीक्षण में मूल अभिलेख मँगाने की सीमाएँ।" },
  { sectionNumber: "22(d) Inserted Proviso (a)", title: "अभिलेख मँगाने से पहले दूसरे पक्ष को कारण बताने का अवसर।" },
  { sectionNumber: "22(d) Inserted Proviso (b)", title: "प्रमाणित प्रतियों से जाँच संभव होने पर मूल अभिलेख न मँगाना।" },

  { sectionNumber: "23", title: "धारा 13(1)(a) के आरोप में संपत्ति और अवधि का विवरण।" },
  { sectionNumber: "23 Proviso", title: "आरोप में शामिल अवधि अधिकतम एक वर्ष।" },

  { sectionNumber: "24", title: "लोपित: रिश्वत देने वाले के बयान से संबंधित पुराना संरक्षण।" },

  { sectionNumber: "25", title: "सैन्य और अन्य निर्धारित कानूनों का संरक्षण।" },
  { sectionNumber: "25(1)", title: "निर्धारित सैन्य और सुरक्षा बल कानूनों का अधिकारक्षेत्र या प्रक्रिया अप्रभावित।" },
  { sectionNumber: "25(2)", title: "उन कानूनों के लिए विशेष न्यायालय को सामान्य आपराधिक न्यायालय मानना।" },

  { sectionNumber: "26", title: "पुराने कानून के विशेष न्यायाधीशों की नियुक्ति और लंबित कार्यवाही जारी रहना।" },

  { sectionNumber: "27", title: "उच्च न्यायालय की अपील और पुनरीक्षण शक्तियाँ।" },

  { sectionNumber: "28", title: "अधिनियम का अन्य कानूनों के अतिरिक्त लागू होना।" },

  { sectionNumber: "29", title: "Criminal Law Amendment Ordinance, 1944 में संशोधन।" },
  { sectionNumber: "29(a)", title: "निर्धारित प्रावधानों में केंद्र सरकार को भी शामिल करना।" },
  { sectionNumber: "29(b)", title: "निर्धारित अवधि को तीन महीने से एक वर्ष करना।" },
  { sectionNumber: "29(c)", title: "अध्यादेश की अनुसूची में संशोधन।" },
  { sectionNumber: "29(c)(i)", title: "अनुसूची के paragraph 1 का लोप।" },
  { sectionNumber: "29(c)(ii)", title: "अनुसूची के paragraphs 2 और 4 में बदलाव।" },
  { sectionNumber: "29(c)(ii)(a)", title: "निर्धारित सरकारी निगम, निकाय, कंपनी और सहायता प्राप्त संस्था शामिल करना।" },
  { sectionNumber: "29(c)(ii)(b)", title: "संबंधित निगम, निकाय, कंपनी और संस्था के संदर्भ जोड़ना।" },
  { sectionNumber: "29(c)(iii)", title: "paragraph 4A में इस अधिनियम के अपराध शामिल करना।" },
  { sectionNumber: "29(c)(iv)", title: "paragraph 5 में item 4A का संदर्भ जोड़ना।" },

  { sectionNumber: "29A", title: "नियम बनाने की शक्ति।" },
  { sectionNumber: "29A(1)", title: "केंद्र सरकार द्वारा अधिनियम लागू करने के नियम बनाना।" },
  { sectionNumber: "29A(2)", title: "नियमों में शामिल किए जाने वाले विषय।" },
  { sectionNumber: "29A(2)(a)", title: "व्यावसायिक संगठनों की भ्रष्टाचार-रोधी प्रक्रियाओं के दिशानिर्देश।" },
  { sectionNumber: "29A(2)(b)", title: "अभियोजन स्वीकृति के दिशानिर्देश।" },
  { sectionNumber: "29A(2)(c)", title: "अन्य निर्धारित किए जाने वाले विषय।" },
  { sectionNumber: "29A(3)", title: "नियम संसद के दोनों सदनों के समक्ष रखना और संशोधन या निरस्तीकरण की प्रक्रिया।" },

  { sectionNumber: "30", title: "पुराने कानूनों का निरसन और पूर्व कार्यवाहियों का संरक्षण।" },
  { sectionNumber: "30(1)", title: "Prevention of Corruption Act, 1947 और Criminal Law Amendment Act, 1952 निरस्त करना।" },
  { sectionNumber: "30(2)", title: "पुराने कानूनों के संगत कार्यों और कार्रवाई का संरक्षण।" },

  { sectionNumber: "31", title: "निरस्त: IPC के कुछ प्रावधानों के लोप से संबंधित संशोधन धारा।" },
];
