import {
  FIRItem,
  FIRStatus,
  MainFIRStatus,
  getMainFIRStatus,
  ComplaintCategory,
  ComplaintPriority,
  FIRCaseDiaryItem,
  FIRDocumentItem,
  ComplaintReportItem,
  FIRTimelineEvent,
  FIRAuditRecord,
  AccusedPerson,
  ComplainantPerson,
} from "@/types";
import { ComplaintService } from "./complaintService";

const FIRS_STORAGE_KEY = "haryana_police_cms_firs_v1";

const INITIAL_MOCK_FIRS: FIRItem[] = [
  {
    id: "fir-001",
    firNumber: "FIR/0014/2026",
    firYear: 2026,
    firDate: "2026-03-28",
    firTime: "11:30",
    policeStation: "Sector 29 Police Station",
    district: "Gurugram",
    state: "Haryana",
    sourceComplaintId: "comp-001",
    sourceComplaintNumber: "COMP/2026/00142",
    cctnsFirNumber: "HR050260014",
    cctnsSyncStatus: "SYNCED",
    category: "PROPERTY_THEFT_BURGLARY",
    categoryDisplay: "Theft / Burglary",
    priority: "URGENT",
    status: "UNDER_INVESTIGATION",
    mainStatus: "Under Investigation",
    actsAndSections: "Sec 303(2), 305 Bharatiya Nyaya Sanhita, 2023 (BNS)",
    majorAct: "Bharatiya Nyaya Sanhita, 2023",
    bnsSections: ["303(2)", "305"],
    incidentDateFrom: "2026-03-27",
    incidentDateTo: "2026-03-27",
    incidentTimeFrom: "21:00",
    incidentTimeTo: "23:30",
    incidentPlace: "Sector 29 Commercial Complex, Near Huda City Centre",
    incidentLandmark: "Opposite Metro Pillar 114",
    distanceFromPs: "1.5 KM East",
    beatNumber: "Beat No. 4",
    incidentDetails: "Complainant reported breaking of car window pane and theft of laptop bag containing HP Pavilion laptop, office identity card, and cash worth Rs. 24,000/- while parked outside market complex.",
    gdEntryNumber: "GD-0042/28-03-2026",
    gdEntryDateTime: "2026-03-28 10:45",
    typeOfInformation: "WRITTEN",
    complainantName: "Vikas Sharma",
    complainantFatherSpouse: "Sh. Ramesh Sharma",
    complainantGender: "MALE",
    complainantAge: 34,
    complainantMobile: "9812345670",
    complainantAddress: "H.No. 402, Sector 29",
    complainantCity: "Gurugram",
    complainantDistrict: "Gurugram",
    complainantState: "Haryana",
    isAccusedKnown: false,
    accusedList: [
      {
        id: "acc-001",
        name: "Unknown suspect (Motorcycle helmet worn)",
        isIdentified: false,
        physicalDescription: "Medium build, black jacket, rider on Pulsar bike without number plate",
      },
    ],
    stolenPropertyDetails: "HP Laptop Serial HP-8849201, Black leather bag, Rs 24,000 currency notes",
    totalPropertyEstimatedValue: 94000,
    registeredBy: "Inspector Rajesh Kumar (SHO)",
    assignedIoId: "eo-002",
    assignedIoName: "SI Neeraj Kumar",
    assignedIoRank: "Sub Inspector",
    assignedIoBeltNumber: "SI/6641",
    assignedIoPhone: "9812300002",
    assignedAt: "2026-03-28 12:00",
    assignedDirections: "Examine CCTV footage from Sector 29 market gate, trace motorcycle route, and record statement of valet security guard.",
    daysPending: 10,
    caseDiaries: [
      {
        id: "cd-001",
        date: "2026-03-28",
        time: "14:00",
        officer: "SI Neeraj Kumar",
        officerRole: "INVESTIGATING_OFFICER",
        summary: "Zimni No. 1: Crime scene inspection and Site Plan preparation",
        details: "Visited Sector 29 parking lot. Prepared site plan (Naksha Mauka). CCTV footage requested from Commercial Complex Management.",
        isAutoGenerated: false,
      },
      {
        id: "cd-002",
        date: "2026-03-30",
        time: "16:30",
        officer: "SI Neeraj Kumar",
        officerRole: "INVESTIGATING_OFFICER",
        summary: "Zimni No. 2: CCTV footage retrieved and analyzed",
        details: "Footage from Camera 3 shows two youths on black Pulsar motorcycle stopping near complainant car at 22:18 hrs. Route leads towards Galleria road.",
        isAutoGenerated: false,
      },
    ],
    documents: [
      {
        id: "doc-001",
        title: "Original Written Complaint / Tehreer",
        fileName: "tehreer_fir_0014_2026.pdf",
        category: "COMPLAINT_COPY",
        uploadedBy: "Inspector Rajesh Kumar",
        uploadedAt: "2026-03-28 11:35",
      },
      {
        id: "doc-002",
        title: "Crime Scene Inspection & Site Plan (Naksha Mauka)",
        fileName: "site_plan_sector29.pdf",
        category: "FIELD_REPORT",
        uploadedBy: "SI Neeraj Kumar",
        uploadedAt: "2026-03-28 17:00",
      },
    ],
    timeline: [
      {
        id: "tl-001",
        date: "2026-03-28 11:30",
        title: "FIR Registered",
        description: "FIR No. FIR/0014/2026 registered under Section 303(2), 305 BNS.",
        actor: "Inspector Rajesh Kumar (SHO)",
        stage: "REGISTERED",
      },
      {
        id: "tl-002",
        date: "2026-03-28 12:00",
        title: "IO Assigned",
        description: "Investigation assigned to SI Neeraj Kumar.",
        actor: "Inspector Rajesh Kumar (SHO)",
        stage: "ASSIGNED",
      },
      {
        id: "tl-003",
        date: "2026-03-28 14:00",
        title: "Zimni No. 1 Recorded",
        description: "Crime scene inspection conducted and site plan prepared.",
        actor: "SI Neeraj Kumar (IO)",
        stage: "FIELD_ENQUIRY",
      },
    ],
    auditTrail: [
      {
        id: "aud-001",
        timestamp: "2026-03-28 11:30",
        action: "FIR_REGISTERED",
        officerName: "Inspector Rajesh Kumar",
        role: "SHO",
        details: "Registered FIR from Complaint COMP/2026/00142",
      },
    ],
    createdAt: "2026-03-28T11:30:00Z",
    updatedAt: "2026-03-30T16:30:00Z",
  },
  {
    id: "fir-002",
    firNumber: "FIR/0015/2026",
    firYear: 2026,
    firDate: "2026-03-31",
    firTime: "15:45",
    policeStation: "Sector 29 Police Station",
    district: "Gurugram",
    state: "Haryana",
    cctnsFirNumber: "HR050260015",
    cctnsSyncStatus: "SYNCED",
    category: "CYBER_CRIME",
    categoryDisplay: "Cyber / Financial Fraud",
    priority: "URGENT",
    status: "UNDER_INVESTIGATION",
    mainStatus: "Under Investigation",
    actsAndSections: "Sec 318(4), 316(2) BNS r/w Sec 66D IT Act",
    majorAct: "Bharatiya Nyaya Sanhita, 2023 & IT Act",
    bnsSections: ["318(4)", "316(2)"],
    specialActs: "Section 66D Information Technology Act, 2000",
    incidentDateFrom: "2026-03-30",
    incidentPlace: "Online - Cyber Space / ICICI Netbanking",
    incidentDetails: "Fraudulent OTP withdrawal amounting to Rs. 1,45,000/- through fake electricity bill payment link sent via WhatsApp.",
    gdEntryNumber: "GD-0078/31-03-2026",
    gdEntryDateTime: "2026-03-31 14:15",
    typeOfInformation: "E_COMPLAINT",
    complainantName: "Anita Verma",
    complainantFatherSpouse: "W/o Sunita Verma",
    complainantGender: "FEMALE",
    complainantAge: 42,
    complainantMobile: "9876543210",
    complainantAddress: "Flat 12B, Palm Grove Heights, Sector 29",
    complainantCity: "Gurugram",
    complainantDistrict: "Gurugram",
    complainantState: "Haryana",
    isAccusedKnown: false,
    accusedList: [
      {
        id: "acc-002",
        name: "Beneficiary Account Holder - Unknown Cyber Gang",
        isIdentified: false,
        phone: "7011982341",
      },
    ],
    stolenPropertyDetails: "Defrauded amount: Rs. 1,45,000/- transferred to A/C 99882211003",
    totalPropertyEstimatedValue: 145000,
    registeredBy: "Inspector Rajesh Kumar (SHO)",
    assignedIoId: "eo-004",
    assignedIoName: "ASI Vikram Singh",
    assignedIoRank: "Assistant Sub Inspector",
    assignedIoBeltNumber: "ASI/4112",
    assignedIoPhone: "9812300004",
    assignedAt: "2026-03-31 16:30",
    assignedDirections: "Liaise with Cyber Cell Gurugram, send freezing notices under Sec 106 BNSS to Canara Bank and payment gateway.",
    daysPending: 7,
    caseDiaries: [
      {
        id: "cd-003",
        date: "2026-03-31",
        time: "17:00",
        officer: "ASI Vikram Singh",
        officerRole: "INVESTIGATING_OFFICER",
        summary: "Zimni No. 1: Bank Account Freezing Notice Dispatched",
        details: "Notice dispatched to Nodal Officer, Canara Bank to debit freeze account 99882211003. Transaction hash sent to 1930 portal.",
        isAutoGenerated: false,
      },
    ],
    documents: [],
    timeline: [
      {
        id: "tl-004",
        date: "2026-03-31 15:45",
        title: "FIR Registered",
        description: "Registered under 318(4) BNS & 66D IT Act.",
        actor: "Inspector Rajesh Kumar (SHO)",
        stage: "REGISTERED",
      },
    ],
    createdAt: "2026-03-31T15:45:00Z",
    updatedAt: "2026-03-31T17:00:00Z",
  },
  {
    id: "fir-003",
    firNumber: "FIR/0010/2026",
    firYear: 2026,
    firDate: "2026-02-15",
    firTime: "10:00",
    policeStation: "Sector 29 Police Station",
    district: "Gurugram",
    state: "Haryana",
    category: "PHYSICAL_ASSAULT_AFFRAY",
    categoryDisplay: "Physical Assault / Hurt",
    priority: "ROUTINE",
    status: "CHARGESHEET_FILED",
    mainStatus: "Chargesheet Filed",
    actsAndSections: "Sec 115(2), 351(2), 352 BNS",
    majorAct: "Bharatiya Nyaya Sanhita, 2023",
    bnsSections: ["115(2)", "351(2)", "352"],
    incidentDateFrom: "2026-02-14",
    incidentPlace: "Main Market, Sector 29",
    incidentDetails: "Altercation between shopkeepers over shop signage leading to simple hurt.",
    gdEntryNumber: "GD-0012/15-02-2026",
    gdEntryDateTime: "2026-02-15 09:30",
    typeOfInformation: "WRITTEN",
    complainantName: "Deepak Yadav",
    complainantFatherSpouse: "Sh. Dharamvir Yadav",
    complainantGender: "MALE",
    complainantAge: 29,
    complainantMobile: "9812998877",
    complainantAddress: "Shop 14, Sector 29",
    complainantCity: "Gurugram",
    complainantDistrict: "Gurugram",
    complainantState: "Haryana",
    isAccusedKnown: true,
    accusedList: [
      {
        id: "acc-003",
        name: "Satish Kumar",
        isIdentified: true,
        address: "Shop 15, Sector 29",
        phone: "9812991122",
      },
    ],
    registeredBy: "Inspector Rajesh Kumar (SHO)",
    assignedIoId: "eo-001",
    assignedIoName: "SI Amit Hooda",
    assignedIoRank: "Sub Inspector",
    daysPending: 0,
    finalFormType: "CHARGESHEET",
    finalFormNumber: "CS/2026/0012",
    finalFormDate: "2026-03-25",
    courtName: "Court of CJM, Gurugram",
    shoDecision: "APPROVE",
    shoDecisionAt: "2026-03-24",
    shoDecisionBy: "Inspector Rajesh Kumar",
    createdAt: "2026-02-15T10:00:00Z",
    updatedAt: "2026-03-25T11:00:00Z",
  },
];

let firsStore: FIRItem[] = [];
const firListeners: (() => void)[] = [];

function notifyListeners() {
  firListeners.forEach((fn) => {
    try {
      fn();
    } catch (e) {
      console.error("Error in FIR listener:", e);
    }
  });
}

function loadFirsFromStorage(): FIRItem[] {
  if (typeof window !== "undefined" && window.localStorage) {
    try {
      const raw = window.localStorage.getItem(FIRS_STORAGE_KEY);
      if (raw) {
        const parsed = JSON.parse(raw);
        if (Array.isArray(parsed) && parsed.length > 0) {
          return parsed;
        }
      }
    } catch (e) {
      console.warn("Failed to read FIRs from localStorage:", e);
    }
  }
  return [...INITIAL_MOCK_FIRS];
}

function saveFirsToStorage(items: FIRItem[]) {
  if (typeof window !== "undefined" && window.localStorage) {
    try {
      window.localStorage.setItem(FIRS_STORAGE_KEY, JSON.stringify(items));
    } catch (e) {
      console.warn("Failed to write FIRs to localStorage:", e);
    }
  }
}

if (typeof window !== "undefined") {
  firsStore = loadFirsFromStorage();
} else {
  firsStore = [...INITIAL_MOCK_FIRS];
}

export const firService = {
  subscribe(listener: () => void): () => void {
    firListeners.push(listener);
    return () => {
      const idx = firListeners.indexOf(listener);
      if (idx > -1) firListeners.splice(idx, 1);
    };
  },

  getAllFirs(): FIRItem[] {
    if (firsStore.length === 0) {
      firsStore = loadFirsFromStorage();
    }
    return [...firsStore].map((fir) => ({
      ...fir,
      mainStatus: getMainFIRStatus(fir),
    }));
  },

  getFirById(id: string): FIRItem | undefined {
    const list = this.getAllFirs();
    return list.find((f) => f.id === id || f.firNumber === id);
  },

  getFirBySourceComplaintId(complaintId: string): FIRItem | undefined {
    const list = this.getAllFirs();
    return list.find((f) => f.sourceComplaintId === complaintId);
  },

  generateNextFirNumber(): { firNumber: string; firYear: number } {
    const year = new Date().getFullYear();
    const list = this.getAllFirs();
    const currentYearFirs = list.filter((f) => f.firYear === year);
    const nextSeq = (currentYearFirs.length + 1).toString().padStart(4, "0");
    return {
      firNumber: `FIR/${nextSeq}/${year}`,
      firYear: year,
    };
  },

  registerFir(input: Partial<FIRItem>): FIRItem {
    const { firNumber, firYear } = input.firNumber
      ? { firNumber: input.firNumber, firYear: input.firYear || new Date().getFullYear() }
      : this.generateNextFirNumber();

    const now = new Date();
    const dateStr = now.toISOString().split("T")[0];
    const timeStr = now.toTimeString().slice(0, 5);

    const newFir: FIRItem = {
      id: input.id || `fir-${Date.now()}`,
      firNumber,
      firYear,
      firDate: input.firDate || dateStr,
      firTime: input.firTime || timeStr,
      policeStation: input.policeStation || "Sector 29 Police Station",
      district: input.district || "Gurugram",
      state: input.state || "Haryana",
      sourceComplaintId: input.sourceComplaintId,
      sourceComplaintNumber: input.sourceComplaintNumber,
      cctnsFirNumber: input.cctnsFirNumber || `HR050${firYear.toString().slice(-2)}${firNumber.split("/")[1] || "0001"}`,
      cctnsSyncStatus: input.cctnsSyncStatus || "PENDING_SYNC",
      category: input.category || "OTHER_GENERAL",
      categoryDisplay: input.categoryDisplay || "General Cognizable Crime",
      priority: input.priority || "URGENT",
      status: input.assignedIoId ? "UNDER_INVESTIGATION" : "UNDER_INVESTIGATION",
      actsAndSections: input.actsAndSections || "Section 303(2) BNS",
      majorAct: input.majorAct || "Bharatiya Nyaya Sanhita, 2023",
      bnsSections: input.bnsSections || [],
      specialActs: input.specialActs,
      incidentDateFrom: input.incidentDateFrom || dateStr,
      incidentDateTo: input.incidentDateTo,
      incidentTimeFrom: input.incidentTimeFrom,
      incidentTimeTo: input.incidentTimeTo,
      incidentPlace: input.incidentPlace || "Police Station Jurisdiction",
      incidentLandmark: input.incidentLandmark,
      distanceFromPs: input.distanceFromPs,
      beatNumber: input.beatNumber,
      incidentDetails: input.incidentDetails || "",
      gdEntryNumber: input.gdEntryNumber,
      gdEntryDateTime: input.gdEntryDateTime,
      typeOfInformation: input.typeOfInformation || "WRITTEN",
      complainantName: input.complainantName || "Unknown Informant",
      complainantFatherSpouse: input.complainantFatherSpouse,
      complainantGender: input.complainantGender || "MALE",
      complainantAge: input.complainantAge,
      complainantMobile: input.complainantMobile || "",
      complainantAddress: input.complainantAddress || "",
      complainantCity: input.complainantCity || "Gurugram",
      complainantDistrict: input.complainantDistrict || "Gurugram",
      complainantState: input.complainantState || "Haryana",
      isAccusedKnown: input.isAccusedKnown ?? false,
      accusedList: input.accusedList || [],
      victimsList: input.victimsList || [],
      stolenPropertyDetails: input.stolenPropertyDetails,
      totalPropertyEstimatedValue: input.totalPropertyEstimatedValue,
      registeredBy: input.registeredBy || "Inspector Rajesh Kumar (SHO)",
      assignedIoId: input.assignedIoId,
      assignedIoName: input.assignedIoName,
      assignedIoRank: input.assignedIoRank,
      assignedIoBeltNumber: input.assignedIoBeltNumber,
      assignedIoPhone: input.assignedIoPhone,
      assignedAt: input.assignedIoId ? `${dateStr} ${timeStr}` : undefined,
      assignedDirections: input.assignedDirections,
      daysPending: 0,
      caseDiaries: input.caseDiaries || [],
      documents: input.documents || [],
      timeline: [
        {
          id: `tl-${Date.now()}`,
          date: `${dateStr} ${timeStr}`,
          title: "FIR Registered",
          description: `FIR No. ${firNumber} registered under ${input.actsAndSections || "applicable BNS sections"}.`,
          actor: input.registeredBy || "SHO Sector 29",
          stage: "REGISTERED",
        },
        ...(input.timeline || []),
      ],
      auditTrail: [
        {
          id: `aud-${Date.now()}`,
          timestamp: `${dateStr} ${timeStr}`,
          action: "FIR_REGISTERED",
          officerName: input.registeredBy || "SHO Sector 29",
          role: "SHO",
          details: input.sourceComplaintNumber
            ? `Registered from Complaint #${input.sourceComplaintNumber}`
            : `Direct FIR Registered under Section 173 BNSS`,
        },
      ],
      createdAt: now.toISOString(),
      updatedAt: now.toISOString(),
    };

    newFir.mainStatus = getMainFIRStatus(newFir);

    firsStore = [newFir, ...firsStore];
    saveFirsToStorage(firsStore);

    if (newFir.sourceComplaintId) {
      try {
        ComplaintService.registerFir(
          newFir.sourceComplaintId,
          newFir.firNumber,
          newFir.actsAndSections,
          newFir.registeredBy,
          "SHO",
          newFir.firDate
        ).catch(() => {});
      } catch (err) {
        console.warn("Could not sync with source complaint:", err);
      }
    }

    notifyListeners();
    return newFir;
  },

  updateFir(firId: string, updates: Partial<FIRItem>): FIRItem | undefined {
    const idx = firsStore.findIndex((f) => f.id === firId || f.firNumber === firId);
    if (idx === -1) return undefined;

    const current = firsStore[idx];
    const updated: FIRItem = {
      ...current,
      ...updates,
      updatedAt: new Date().toISOString(),
    };
    updated.mainStatus = getMainFIRStatus(updated);

    firsStore[idx] = updated;
    saveFirsToStorage(firsStore);
    notifyListeners();
    return updated;
  },

  assignIo(
    firId: string,
    ioId: string,
    ioName: string,
    rank?: string,
    directions?: string,
    assignedBy?: string
  ): FIRItem | undefined {
    const fir = this.getFirById(firId);
    if (!fir) return undefined;

    const now = new Date();
    const dateStr = now.toISOString().split("T")[0];
    const timeStr = now.toTimeString().slice(0, 5);

    const timelineItem: FIRTimelineEvent = {
      id: `tl-${Date.now()}`,
      date: `${dateStr} ${timeStr}`,
      title: "IO Assigned",
      description: `Investigation assigned to ${ioName} (${rank || "IO"}). Directions: ${directions || "Conduct thorough investigation as per procedure."}`,
      actor: assignedBy || "SHO Sector 29",
      stage: "ASSIGNED",
    };

    const auditItem: FIRAuditRecord = {
      id: `aud-${Date.now()}`,
      timestamp: `${dateStr} ${timeStr}`,
      action: "IO_ASSIGNED",
      officerName: assignedBy || "SHO",
      role: "SHO",
      details: `Assigned IO: ${ioName} (${rank || "IO"})`,
    };

    return this.updateFir(firId, {
      assignedIoId: ioId,
      assignedIoName: ioName,
      assignedIoRank: rank || "Sub Inspector",
      assignedAt: `${dateStr} ${timeStr}`,
      assignedDirections: directions,
      status: "UNDER_INVESTIGATION",
      timeline: [timelineItem, ...(fir.timeline || [])],
      auditTrail: [auditItem, ...(fir.auditTrail || [])],
    });
  },

  addCaseDiary(firId: string, note: FIRCaseDiaryItem): FIRItem | undefined {
    const fir = this.getFirById(firId);
    if (!fir) return undefined;

    const caseDiaries = [note, ...(fir.caseDiaries || [])];
    const timelineItem: FIRTimelineEvent = {
      id: `tl-${Date.now()}`,
      date: `${note.date} ${note.time}`,
      title: note.summary || "Case Diary (Zimni) Recorded",
      description: note.details?.slice(0, 160) || "Case Diary entry submitted by IO.",
      actor: note.officer,
      stage: "FIELD_ENQUIRY",
    };

    return this.updateFir(firId, {
      caseDiaries,
      timeline: [timelineItem, ...(fir.timeline || [])],
    });
  },

  addDocument(firId: string, doc: FIRDocumentItem): FIRItem | undefined {
    const fir = this.getFirById(firId);
    if (!fir) return undefined;

    const documents = [doc, ...(fir.documents || [])];
    return this.updateFir(firId, { documents });
  },

  deleteDocument(firId: string, docId: string): FIRItem | undefined {
    const fir = this.getFirById(firId);
    if (!fir) return undefined;

    const documents = (fir.documents || []).filter((d) => d.id !== docId);
    return this.updateFir(firId, { documents });
  },

  addReport(firId: string, report: ComplaintReportItem): FIRItem | undefined {
    const fir = this.getFirById(firId);
    if (!fir) return undefined;

    const reports = [report, ...(fir.reports || [])];
    return this.updateFir(firId, { reports });
  },

  deleteReport(firId: string, reportId: string): FIRItem | undefined {
    const fir = this.getFirById(firId);
    if (!fir) return undefined;

    const reports = (fir.reports || []).filter((r) => r.id !== reportId);
    return this.updateFir(firId, { reports });
  },

  submitFinalForm(
    firId: string,
    formType: "CHARGESHEET" | "CLOSURE" | "UNTRACED" | "CANCELLED",
    courtName: string,
    submittedBy: string,
    summary: string
  ): FIRItem | undefined {
    const fir = this.getFirById(firId);
    if (!fir) return undefined;

    const now = new Date();
    const dateStr = now.toISOString().split("T")[0];
    const timeStr = now.toTimeString().slice(0, 5);
    const formNum = `${formType === "CHARGESHEET" ? "CS" : "FR"}/${fir.firYear}/${Date.now().toString().slice(-4)}`;

    const status: FIRStatus =
      formType === "CHARGESHEET"
        ? "CHARGESHEET_FILED"
        : formType === "CLOSURE"
        ? "CLOSURE_REPORT_FILED"
        : formType === "UNTRACED"
        ? "UNTRACED"
        : "CANCELLED";

    const timelineItem: FIRTimelineEvent = {
      id: `tl-${Date.now()}`,
      date: `${dateStr} ${timeStr}`,
      title: `Final Report Filed: ${formType} u/s 193 BNSS`,
      description: `Report Number: ${formNum} forwarded for submission before ${courtName}. Summary: ${summary.slice(0, 150)}`,
      actor: submittedBy,
      stage: "FINAL_REPORT",
    };

    return this.updateFir(firId, {
      finalFormType: formType,
      finalFormNumber: formNum,
      finalFormDate: dateStr,
      courtName,
      status,
      timeline: [timelineItem, ...(fir.timeline || [])],
    });
  },

  addAuditRecord(firId: string, action: string, details: string, officerName?: string, role?: string) {
    const fir = this.getFirById(firId);
    if (!fir) return;

    const now = new Date();
    const item: FIRAuditRecord = {
      id: `aud-${Date.now()}`,
      timestamp: `${now.toISOString().split("T")[0]} ${now.toTimeString().slice(0, 5)}`,
      action,
      officerName: officerName || "Officer",
      role: role || "SHO",
      details,
    };

    this.updateFir(firId, {
      auditTrail: [item, ...(fir.auditTrail || [])],
    });
  },
};
